import { jsPDF } from 'jspdf';

interface GenerateCareInstructionsPDFOptions {
  organizationName: string;
  clientName: string;
  instructionTitle: string;
  instructionContent: string;
  date?: string;
}

export function generateCareInstructionsPDF({
  organizationName,
  clientName,
  instructionTitle,
  instructionContent,
  date = new Date().toLocaleDateString('he-IL'),
}: GenerateCareInstructionsPDFOptions): jsPDF {
  const doc = new jsPDF();

  let yPos = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Title - Organization Name
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(organizationName, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Subtitle - Care Instructions + Date
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`Care Instructions - ${date}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Client Name
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Client: ${clientName}`, margin, yPos);
  yPos += 15;

  // Instruction Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(instructionTitle, margin, yPos);
  yPos += 12;

  // Instruction Content
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  // Split content into lines to fit page width
  const contentLines = doc.splitTextToSize(instructionContent, maxWidth);
  
  contentLines.forEach((line: string) => {
    // Check if we need a new page
    if (yPos > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.text(line, margin, yPos);
    yPos += 7;
  });

  // Footer
  const footer = `Generated by ${organizationName} - ${date}`;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(footer, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename);
}

export function getWhatsAppMessage(organizationName: string, instructionTitle: string): string {
  return `היי! 👋\n\nתודה שביקרת ב${organizationName}.\n\nמצורף מסמך PDF עם הוראות טיפול: ${instructionTitle}\n\nנשמח לראותך שוב! 🌟`;
}

export function openWhatsAppWithMessage(phoneNumber: string, message: string) {
  // Remove non-numeric characters from phone
  const cleanPhone = phoneNumber.replace(/\D/g, '');
  
  // WhatsApp URL with international format (972 for Israel)
  const whatsappURL = `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
  
  // Open in new window/tab
  window.open(whatsappURL, '_blank');
}
