/**
 * self-healing/github.ts
 * GitHub API: создание ветки, коммит фикса + теста, PR, мерж
 */

const GH_TOKEN = () => process.env.GITHUB_TOKEN!
const GH_OWNER = () => process.env.GITHUB_OWNER ?? 'Creepie132'
const GH_REPO  = () => process.env.GITHUB_REPO ?? 'trinity'
const BASE_BRANCH = 'main'

const ghFetch = async (path: string, init?: RequestInit) => {
  const res = await fetch(`https://api.github.com/repos/${GH_OWNER()}/${GH_REPO()}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${GH_TOKEN()}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init?.headers ?? {}),
    },
  })
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub ${res.status} on ${path}: ${body}`)
  }
  return res.json()
}

/** Получить SHA последнего коммита в main */
async function getMainSha(): Promise<string> {
  const data = await ghFetch(`/git/ref/heads/${BASE_BRANCH}`)
  return data.object.sha as string
}

/** Получить содержимое и SHA файла для последующего обновления */
export async function getFileContent(filePath: string): Promise<{ content: string; sha: string }> {
  const data = await ghFetch(`/contents/${filePath}`)
  const content = Buffer.from(data.content as string, 'base64').toString('utf-8')
  return { content, sha: data.sha as string }
}

/** Создать ветку auto-fix/bug-{errorId} */
export async function createFixBranch(errorId: string): Promise<string> {
  const mainSha = await getMainSha()
  const branchName = `auto-fix/bug-${errorId}`

  await ghFetch('/git/refs', {
    method: 'POST',
    body: JSON.stringify({
      ref: `refs/heads/${branchName}`,
      sha: mainSha,
    }),
  })

  return branchName
}

/** Закоммитить исправленный файл + тест в ветку */
export async function commitFix(params: {
  branchName: string
  filePath: string
  fixedCode: string
  testFileName: string
  testCode: string
  errorId: string
}): Promise<void> {
  const { branchName, filePath, fixedCode, testFileName, testCode, errorId } = params

  // Получаем SHA текущего файла (для update)
  const fileData = await ghFetch(`/contents/${filePath}?ref=${branchName}`)
  const fileSha = fileData.sha as string

  // Обновляем основной файл
  await ghFetch(`/contents/${filePath}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `fix: auto-heal bug-${errorId} in ${filePath}`,
      content: Buffer.from(fixedCode).toString('base64'),
      sha: fileSha,
      branch: branchName,
    }),
  })

  // Создаём тестовый файл (новый — SHA не нужен)
  await ghFetch(`/contents/${testFileName}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `test: add heal test for bug-${errorId}`,
      content: Buffer.from(testCode).toString('base64'),
      branch: branchName,
    }),
  })
}

/** Создать Pull Request */
export async function createPullRequest(params: {
  branchName: string
  errorId: string
  analysis: string
}): Promise<{ prUrl: string; prNumber: number }> {
  const data = await ghFetch('/pulls', {
    method: 'POST',
    body: JSON.stringify({
      title: `🤖 Auto-heal: bug-${params.errorId}`,
      head: params.branchName,
      base: BASE_BRANCH,
      body: `## Automated Bug Fix\n\n**Error ID:** ${params.errorId}\n\n**Analysis:**\n${params.analysis}\n\n> Generated by Trinity Self-Healing System`,
    }),
  })
  return { prUrl: data.html_url as string, prNumber: data.number as number }
}

/** Замержить PR в main (squash) */
export async function mergePullRequest(prNumber: number, errorId: string): Promise<void> {
  await ghFetch(`/pulls/${prNumber}/merge`, {
    method: 'PUT',
    body: JSON.stringify({
      commit_title: `fix: auto-heal bug-${errorId} [skip ci]`,
      merge_method: 'squash',
    }),
  })
}

/** Удалить ветку после мержа */
export async function deleteBranch(branchName: string): Promise<void> {
  await ghFetch(`/git/refs/heads/${branchName}`, { method: 'DELETE' })
}
