'use client'

import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Language = 'he' | 'ru'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: 'rtl' | 'ltr'
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations: Record<Language, Record<string, string>> = {
  he: {
    // Navigation
    'nav.dashboard': 'דשבורד',
    'nav.clients': 'לקוחות',
    'nav.payments': 'תשלומים',
    'nav.sms': 'הודעות SMS',
    'nav.stats': 'סטטיסטיקה',
    'nav.partners': 'הצעות שותפים',
    'nav.settings': 'הגדרות',
    'nav.admin': 'פאנל ניהול',
    'nav.darkMode': 'מצב כהה',
    'nav.lightMode': 'מצב בהיר',
    'nav.myProfile': 'הפרופיל שלי',
    'nav.logout': 'יציאה מהמערכת',
    'nav.backToMain': 'חזרה לדשבורד הראשי',
    
    // Admin Navigation
    'admin.dashboard': 'לוח בקרה',
    'admin.organizations': 'ארגונים',
    'admin.billing': 'חיובים',
    'admin.ads': 'פרסום',
    'admin.settings': 'הגדרות',
    
    // Admin Dashboard
    'admin.welcome': 'לוח בקרה - מערכת ניהול',
    'admin.subtitle': 'מבט כללי על המערכת והארגונים',
    'admin.totalOrgs': 'סה״כ ארגונים',
    'admin.activeOrgs': 'ארגונים פעילים',
    'admin.totalUsers': 'סה״כ משתמשים',
    'admin.monthlyRevenue': 'הכנסות חודשיות',
    'admin.recentOrgs': 'ארגונים אחרונים',
    'admin.growth': 'צמיחה',
    'admin.systemHealth': 'מצב המערכת',
    
    // Admin Organizations
    'admin.orgs.title': 'ניהול ארגונים',
    'admin.orgs.subtitle': 'צפייה וניהול של כל הארגונים במערכת',
    'admin.orgs.addNew': 'הוסף ארגון',
    'admin.orgs.name': 'שם ארגון',
    'admin.orgs.status': 'סטטוס',
    'admin.orgs.active': 'פעיל',
    'admin.orgs.blocked': 'חסום',
    'admin.orgs.suspended': 'מושהה',
    'admin.orgs.users': 'משתמשים',
    'admin.orgs.created': 'נוצר',
    'admin.orgs.plan': 'תוכנית',
    'admin.orgs.basic': 'בסיסי',
    'admin.orgs.premium': 'פרימיום',
    'admin.orgs.enterprise': 'ארגוני',
    'admin.orgs.features': 'פיצ׳רים',
    'admin.orgs.block': 'חסום',
    'admin.orgs.unblock': 'בטל חסימה',
    'admin.orgs.details': 'פרטי ארגון',
    
    // Admin Billing
    'admin.billing.title': 'ניהול חיובים',
    'admin.billing.subtitle': 'מעקב אחר תשלומים ומנויים',
    'admin.billing.invoice': 'חשבונית',
    'admin.billing.paid': 'שולם',
    'admin.billing.unpaid': 'לא שולם',
    'admin.billing.overdue': 'באיחור',
    'admin.billing.dueDate': 'תאריך תשלום',
    'admin.billing.total': 'סה״כ',
    
    // Admin Ads
    'admin.ads.title': 'ניהול פרסומות',
    'admin.ads.subtitle': 'יצירה וניהול של באנרים פרסומיים',
    'admin.ads.addNew': 'הוסף פרסומת',
    'admin.ads.title.field': 'כותרת',
    'admin.ads.description': 'תיאור',
    'admin.ads.image': 'תמונה',
    'admin.ads.url': 'קישור',
    'admin.ads.active': 'פעיל',
    'admin.ads.inactive': 'לא פעיל',
    'admin.ads.impressions': 'צפיות',
    'admin.ads.clicks': 'קליקים',
    
    // Settings
    'settings.title': 'הגדרות',
    'settings.subtitle': 'נהל את העדפות המערכת שלך',
    'settings.display': 'תצוגה',
    'settings.display.desc': 'צבעים, עיצוב, תבניות',
    'settings.language': 'שפה',
    'settings.language.desc': 'שפת ממשק וכיוון תצוגה',
    'settings.advanced': 'הגדרות נוספות',
    'settings.advanced.desc': 'הגדרות מתקדמות יתווספו בעתיד',
    
    // Display Settings
    'display.title': 'הגדרות תצוגה',
    'display.subtitle': 'התאם את המראה והתחושה של הממשק',
    'display.back': 'חזרה להגדרות',
    'display.colorTheme': 'ערכת נושא חזותית',
    'display.colorTheme.desc': 'בחר את צבע הממשק המועדף עליך',
    'display.darkMode': 'מצב כהה',
    'display.darkMode.desc': 'עבור לממשק כהה (Dark Mode)',
    'display.layout': 'סגנון תצוגה (Layout)',
    'display.layout.desc': 'שנה את אופן התצוגה של הנתונים והכרטיסים',
    'display.customize': 'התאמה מתקדמת',
    'display.customize.desc': 'שליטה מלאה על כל פרט בממשק',
    'display.customize.btn': 'פתח התאמה מתקדמת',
    
    // Language Settings
    'language.title': 'הגדרות שפה',
    'language.subtitle': 'שנה את שפת הממשק וכיוון התצוגה',
    'language.back': 'חזרה להגדרות',
    'language.select': 'בחר שפה',
    'language.select.desc': 'שפת הממשק תשתנה מיד',
    'language.hebrew': 'עברית',
    'language.russian': 'Русский',
    'language.direction': 'כיוון תצוגה',
    'language.rtl': 'ימין לשמאל (RTL)',
    'language.ltr': 'שמאל לימין (LTR)',
    
    // Themes
    'theme.default': 'כחול (ברירת מחדל)',
    'theme.purple': 'סגול',
    'theme.green': 'ירוק',
    'theme.orange': 'כתום',
    'theme.pink': 'ורוד',
    'theme.dark': 'כהה (אינדיגו)',
    
    // Layouts
    'layout.classic': 'קלאסי',
    'layout.classic.desc': 'טבלאות ומינימליזם',
    'layout.modern': 'מודרני',
    'layout.modern.desc': 'כרטיסים גדולים וצללים',
    'layout.compact': 'צפוף',
    'layout.compact.desc': 'יותר מידע במסך',
    
    // Dashboard
    'dashboard.welcome': 'ברוכים הבאים ל-Trinity',
    'dashboard.subtitle': 'מערכת ניהול לקוחות, תשלומים והודעות SMS',
    'dashboard.totalClients': 'סה״כ לקוחות',
    'dashboard.visitsMonth': 'ביקורים החודש',
    'dashboard.revenueMonth': 'הכנסות החודש',
    'dashboard.inactiveClients': 'לקוחות לא פעילים',
    'dashboard.inactiveNote': '30+ ימים ללא ביקור',
    'dashboard.quickActions': 'פעולות מהירות',
    'dashboard.gettingStarted': 'התחלה מהירה',
    'dashboard.step1': 'הוסף לקוחות חדשים בעמוד "לקוחות"',
    'dashboard.step2': 'צור קישורי תשלום בעמוד "תשלומים"',
    'dashboard.step3': 'שלח הודעות SMS ללקוחות בעמוד "הודעות SMS"',
    'dashboard.step4': 'עקוב אחר הנתונים והגרפים בעמוד "סטטיסטיקה"',
    'dashboard.viewFullStats': 'צפה בסטטיסטיקה מלאה',
    
    // Clients
    'clients.title': 'לקוחות',
    'clients.subtitle': 'ניהול לקוחות והיסטוריית ביקורים',
    'clients.addNew': 'הוסף לקוח חדש',
    'clients.search': 'חיפוש לפי שם, טלפון או אימייל',
    'clients.searchPlaceholder': 'חיפוש...',
    'clients.name': 'שם',
    'clients.firstName': 'שם פרטי',
    'clients.lastName': 'שם משפחה',
    'clients.phone': 'טלפון',
    'clients.email': 'אימייל',
    'clients.address': 'כתובת',
    'clients.birthDate': 'תאריך לידה',
    'clients.lastVisit': 'ביקור אחרון',
    'clients.totalSpent': 'סה״כ הוצאות',
    'clients.visits': 'ביקורים',
    'clients.actions': 'פעולות',
    'clients.edit': 'עריכה',
    'clients.delete': 'מחיקה',
    'clients.noClients': 'לא נמצאו לקוחות',
    'clients.addFirst': 'הוסף את הלקוח הראשון שלך',
    'clients.noResults': 'לא נמצאו תוצאות',
    'clients.tryDifferent': 'נסה מילות חיפוש אחרות',
    'clients.details': 'פרטי לקוח',
    'clients.history': 'היסטוריית ביקורים',
    'clients.addVisit': 'הוסף ביקור',
    'clients.date': 'תאריך',
    'clients.service': 'שירות',
    'clients.amount': 'סכום',
    'clients.notes': 'הערות',
    'clients.noOrgFound': 'לא נמצא ארגון למשתמש',
    
    // Payments
    'payments.title': 'תשלומים',
    'payments.subtitle': 'ניהול תשלומים והכנסות',
    'payments.addNew': 'הוסף תשלום',
    'payments.createLink': 'צור קישור לתשלום',
    'payments.createFirst': 'צור קישור לתשלום ראשון',
    'payments.client': 'לקוח',
    'payments.amount': 'סכום',
    'payments.status': 'סטטוס',
    'payments.paid': 'שולם',
    'payments.pending': 'ממתין',
    'payments.failed': 'נכשל',
    'payments.refunded': 'הוחזר',
    'payments.cancelled': 'בוטל',
    'payments.method': 'אמצעי תשלום',
    'payments.cash': 'מזומן',
    'payments.card': 'כרטיס אשראי',
    'payments.bankTransfer': 'העברה בנקאית',
    'payments.total': 'סה״כ',
    'payments.filter': 'סינון',
    'payments.all': 'הכל',
    'payments.fromDate': 'מתאריך',
    'payments.toDate': 'עד תאריך',
    'payments.totalMonth': 'סך התשלומים החודש',
    'payments.successfulTransactions': 'עסקאות מוצלחות',
    'payments.avgTransaction': 'ממוצע לעסקה',
    'payments.noPayments': 'אין תשלומים',
    'payments.unknown': 'לא ידוע',
    'payments.copyLink': 'העתק קישור',
    'payments.openLink': 'פתח קישור',
    'payments.transactionId': 'מזהה עסקה',
    'payments.linkCopied': 'הקישור הועתק ללוח',
    'payments.successMessage': 'התשלום בוצע בהצלחה!',
    'payments.failedMessage': 'התשלום נכשל',
    
    // SMS
    'sms.title': 'הודעות SMS',
    'sms.subtitle': 'נהל רסלות SMS ללקוחות',
    'sms.sendNew': 'שלח הודעה חדשה',
    'sms.recipient': 'נמען',
    'sms.recipients': 'מקבלים',
    'sms.message': 'תוכן ההודעה',
    'sms.send': 'שלח',
    'sms.history': 'היסטוריית רסלות',
    'sms.sent': 'נשלחו',
    'sms.failed': 'נכשלו',
    'sms.delivered': 'נמסר',
    'sms.completed': 'הושלם',
    'sms.sending': 'שולח',
    'sms.draft': 'טיוטה',
    'sms.selectClient': 'בחר לקוח',
    'sms.messagePlaceholder': 'הקלד את ההודעה כאן...',
    'sms.remaining': 'תווים נותרים',
    'sms.noCampaigns': 'אין רסלות',
    'sms.createNew': 'צור רסלה חדשה למעלה',
    
    // Stats
    'stats.title': 'סטטיסטיקה',
    'stats.subtitle': 'מבט כללי על העסק',
    'stats.revenue': 'הכנסות',
    'stats.revenueByMonth': 'הכנסות לפי חודש',
    'stats.visitsByMonth': 'ביקורים לפי חודש',
    'stats.byMonth': 'לפי חודש',
    'stats.byService': 'לפי שירות',
    'stats.topClients': '5 הלקוחות המובילים',
    'stats.totalPayments': 'סה״כ תשלומים',
    'stats.trends': 'מגמות',
    'stats.export': 'ייצוא נתונים',
    'stats.noData': 'אין נתונים להצגה',
    
    // Partners
    'partners.title': 'הצעות שותפים',
    'partners.subtitle': 'גלה מוצרים ושירותים מומלצים לעסק שלך',
    'partners.noOffers': 'אין הצעות זמינות כרגע',
    'partners.checkLater': 'בדוק שוב מאוחר יותר',
    'partners.details': 'לפרטים',
    
    // Common
    'common.loading': 'טוען נתונים...',
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.close': 'סגור',
    'common.back': 'חזרה',
    'common.logout': 'התנתק',
    'common.add': 'הוסף',
    'common.edit': 'ערוך',
    'common.delete': 'מחק',
    'common.view': 'צפה',
    'common.search': 'חיפוש',
    'common.filter': 'סנן',
    'common.export': 'ייצא',
    'common.import': 'ייבא',
    'common.refresh': 'רענן',
    'common.submit': 'שלח',
    'common.reset': 'אפס',
    'common.confirm': 'אישור',
    'common.yes': 'כן',
    'common.no': 'לא',
    'common.ok': 'אישור',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.warning': 'אזהרה',
    'common.info': 'מידע',
    'common.required': 'שדה חובה',
    'common.optional': 'אופציונלי',
    'common.select': 'בחר',
    'common.selectAll': 'בחר הכל',
    'common.deselectAll': 'בטל בחירת הכל',
    'common.noData': 'אין נתונים',
    'common.noResults': 'אין תוצאות',
    'common.showing': 'מציג',
    'common.of': 'מתוך',
    'common.items': 'פריטים',
    'common.page': 'עמוד',
    'common.perPage': 'לעמוד',
    'common.total': 'סה״כ',
    'common.actions': 'פעולות',
    'common.date': 'תאריך',
    'common.time': 'שעה',
    'common.status': 'סטטוס',
    'common.active': 'פעיל',
    'common.inactive': 'לא פעיל',
    'common.enabled': 'מופעל',
    'common.disabled': 'מושבת',
    'common.description': 'תיאור',
    'common.name': 'שם',
    'common.email': 'אימייל',
    'common.phone': 'טלפון',
    'common.address': 'כתובת',
    'common.notes': 'הערות',
    'common.created': 'נוצר',
    'common.updated': 'עודכן',
    'common.createdAt': 'תאריך יצירה',
    'common.updatedAt': 'תאריך עדכון',
    'common.deleteConfirm': 'האם אתה בטוח שברצונך למחוק?',
    'common.cannotUndo': 'לא ניתן לבטל פעולה זו',
    'common.saving': 'שומר...',
    'common.notAvailable': 'לא זמין',
    
    // Error page
    'error.message': 'משהו השתבש. אנא נסה שוב או פנה לתמיכה.',
    'error.retry': 'נסה שוב',
    'error.backHome': 'חזור לדף הבית',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Дашборд',
    'nav.clients': 'Клиенты',
    'nav.payments': 'Платежи',
    'nav.sms': 'SMS сообщения',
    'nav.stats': 'Статистика',
    'nav.partners': 'Партнёрские предложения',
    'nav.settings': 'Настройки',
    'nav.admin': 'Панель управления',
    'nav.darkMode': 'Тёмная тема',
    'nav.lightMode': 'Светлая тема',
    'nav.myProfile': 'Мой профиль',
    'nav.logout': 'Выйти из системы',
    'nav.backToMain': 'Вернуться в главный дашборд',
    
    // Admin Navigation
    'admin.dashboard': 'Панель управления',
    'admin.organizations': 'Организации',
    'admin.billing': 'Оплата',
    'admin.ads': 'Реклама',
    'admin.settings': 'Настройки',
    
    // Admin Dashboard
    'admin.welcome': 'Панель управления - Система управления',
    'admin.subtitle': 'Общий обзор системы и организаций',
    'admin.totalOrgs': 'Всего организаций',
    'admin.activeOrgs': 'Активных организаций',
    'admin.totalUsers': 'Всего пользователей',
    'admin.monthlyRevenue': 'Месячный доход',
    'admin.recentOrgs': 'Последние организации',
    'admin.growth': 'Рост',
    'admin.systemHealth': 'Состояние системы',
    
    // Admin Organizations
    'admin.orgs.title': 'Управление организациями',
    'admin.orgs.subtitle': 'Просмотр и управление всеми организациями в системе',
    'admin.orgs.addNew': 'Добавить организацию',
    'admin.orgs.name': 'Название организации',
    'admin.orgs.status': 'Статус',
    'admin.orgs.active': 'Активна',
    'admin.orgs.blocked': 'Заблокирована',
    'admin.orgs.suspended': 'Приостановлена',
    'admin.orgs.users': 'Пользователи',
    'admin.orgs.created': 'Создана',
    'admin.orgs.plan': 'План',
    'admin.orgs.basic': 'Базовый',
    'admin.orgs.premium': 'Премиум',
    'admin.orgs.enterprise': 'Корпоративный',
    'admin.orgs.features': 'Возможности',
    'admin.orgs.block': 'Заблокировать',
    'admin.orgs.unblock': 'Разблокировать',
    'admin.orgs.details': 'Детали организации',
    
    // Admin Billing
    'admin.billing.title': 'Управление платежами',
    'admin.billing.subtitle': 'Отслеживание платежей и подписок',
    'admin.billing.invoice': 'Счёт',
    'admin.billing.paid': 'Оплачено',
    'admin.billing.unpaid': 'Не оплачено',
    'admin.billing.overdue': 'Просрочено',
    'admin.billing.dueDate': 'Срок оплаты',
    'admin.billing.total': 'Итого',
    
    // Admin Ads
    'admin.ads.title': 'Управление рекламой',
    'admin.ads.subtitle': 'Создание и управление рекламными баннерами',
    'admin.ads.addNew': 'Добавить рекламу',
    'admin.ads.title.field': 'Заголовок',
    'admin.ads.description': 'Описание',
    'admin.ads.image': 'Изображение',
    'admin.ads.url': 'Ссылка',
    'admin.ads.active': 'Активна',
    'admin.ads.inactive': 'Неактивна',
    'admin.ads.impressions': 'Просмотры',
    'admin.ads.clicks': 'Клики',
    
    // Settings
    'settings.title': 'Настройки',
    'settings.subtitle': 'Управляйте настройками системы',
    'settings.display': 'Внешний вид',
    'settings.display.desc': 'Цвета, дизайн, темы',
    'settings.language': 'Язык',
    'settings.language.desc': 'Язык интерфейса и направление текста',
    'settings.advanced': 'Дополнительные настройки',
    'settings.advanced.desc': 'Будут добавлены в будущем',
    
    // Display Settings
    'display.title': 'Настройки внешнего вида',
    'display.subtitle': 'Настройте внешний вид интерфейса',
    'display.back': 'Назад к настройкам',
    'display.colorTheme': 'Цветовая тема',
    'display.colorTheme.desc': 'Выберите предпочитаемый цвет интерфейса',
    'display.darkMode': 'Тёмная тема',
    'display.darkMode.desc': 'Переключить на тёмный интерфейс (Dark Mode)',
    'display.layout': 'Стиль отображения (Layout)',
    'display.layout.desc': 'Измените способ отображения данных и карточек',
    'display.customize': 'Расширенная настройка',
    'display.customize.desc': 'Полный контроль над каждой деталью интерфейса',
    'display.customize.btn': 'Открыть расширенные настройки',
    
    // Language Settings
    'language.title': 'Настройки языка',
    'language.subtitle': 'Измените язык интерфейса и направление отображения',
    'language.back': 'Назад к настройкам',
    'language.select': 'Выберите язык',
    'language.select.desc': 'Интерфейс сразу переключится на выбранный язык',
    'language.hebrew': 'עברית',
    'language.russian': 'Русский',
    'language.direction': 'Направление текста',
    'language.rtl': 'Справа налево (RTL)',
    'language.ltr': 'Слева направо (LTR)',
    
    // Themes
    'theme.default': 'Синий (по умолчанию)',
    'theme.purple': 'Фиолетовый',
    'theme.green': 'Зелёный',
    'theme.orange': 'Оранжевый',
    'theme.pink': 'Розовый',
    'theme.dark': 'Тёмный (индиго)',
    
    // Layouts
    'layout.classic': 'Классический',
    'layout.classic.desc': 'Таблицы и минимализм',
    'layout.modern': 'Современный',
    'layout.modern.desc': 'Большие карточки с тенями',
    'layout.compact': 'Компактный',
    'layout.compact.desc': 'Больше информации на экране',
    
    // Dashboard
    'dashboard.welcome': 'Добро пожаловать в Trinity',
    'dashboard.subtitle': 'Система управления клиентами, платежами и SMS',
    'dashboard.totalClients': 'Всего клиентов',
    'dashboard.visitsMonth': 'Визиты за месяц',
    'dashboard.revenueMonth': 'Доход за месяц',
    'dashboard.inactiveClients': 'Неактивные клиенты',
    'dashboard.inactiveNote': '30+ дней без визита',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.gettingStarted': 'Быстрый старт',
    'dashboard.step1': 'Добавьте новых клиентов на странице "Клиенты"',
    'dashboard.step2': 'Создайте ссылки для оплаты на странице "Платежи"',
    'dashboard.step3': 'Отправляйте SMS клиентам на странице "SMS сообщения"',
    'dashboard.step4': 'Отслеживайте данные и графики на странице "Статистика"',
    'dashboard.viewFullStats': 'Посмотреть полную статистику',
    
    // Clients
    'clients.title': 'Клиенты',
    'clients.subtitle': 'Управление клиентами и история визитов',
    'clients.addNew': 'Добавить нового клиента',
    'clients.search': 'Поиск по имени, телефону или email',
    'clients.searchPlaceholder': 'Поиск...',
    'clients.name': 'Имя',
    'clients.firstName': 'Имя',
    'clients.lastName': 'Фамилия',
    'clients.phone': 'Телефон',
    'clients.email': 'Email',
    'clients.address': 'Адрес',
    'clients.birthDate': 'Дата рождения',
    'clients.lastVisit': 'Последний визит',
    'clients.totalSpent': 'Всего потрачено',
    'clients.visits': 'Визиты',
    'clients.actions': 'Действия',
    'clients.edit': 'Редактировать',
    'clients.delete': 'Удалить',
    'clients.noClients': 'Клиенты не найдены',
    'clients.addFirst': 'Добавьте вашего первого клиента',
    'clients.noResults': 'Нет результатов',
    'clients.tryDifferent': 'Попробуйте другие ключевые слова',
    'clients.details': 'Детали клиента',
    'clients.history': 'История визитов',
    'clients.addVisit': 'Добавить визит',
    'clients.date': 'Дата',
    'clients.service': 'Услуга',
    'clients.amount': 'Сумма',
    'clients.notes': 'Заметки',
    'clients.noOrgFound': 'Организация для пользователя не найдена',
    
    // Payments
    'payments.title': 'Платежи',
    'payments.subtitle': 'Управление платежами и доходами',
    'payments.addNew': 'Добавить платёж',
    'payments.createLink': 'Создать ссылку для оплаты',
    'payments.createFirst': 'Создать первую ссылку для оплаты',
    'payments.client': 'Клиент',
    'payments.amount': 'Сумма',
    'payments.status': 'Статус',
    'payments.paid': 'Оплачено',
    'payments.pending': 'Ожидание',
    'payments.failed': 'Ошибка',
    'payments.refunded': 'Возвращено',
    'payments.cancelled': 'Отменено',
    'payments.method': 'Способ оплаты',
    'payments.cash': 'Наличные',
    'payments.card': 'Кредитная карта',
    'payments.bankTransfer': 'Банковский перевод',
    'payments.total': 'Итого',
    'payments.filter': 'Фильтр',
    'payments.all': 'Все',
    'payments.fromDate': 'С даты',
    'payments.toDate': 'До даты',
    'payments.totalMonth': 'Всего платежей за месяц',
    'payments.successfulTransactions': 'Успешных транзакций',
    'payments.avgTransaction': 'Средняя транзакция',
    'payments.noPayments': 'Нет платежей',
    'payments.unknown': 'Неизвестно',
    'payments.copyLink': 'Скопировать ссылку',
    'payments.openLink': 'Открыть ссылку',
    'payments.transactionId': 'ID транзакции',
    'payments.linkCopied': 'Ссылка скопирована в буфер обмена',
    'payments.successMessage': 'Платёж успешно выполнен!',
    'payments.failedMessage': 'Ошибка платежа',
    
    // SMS
    'sms.title': 'SMS сообщения',
    'sms.subtitle': 'Управление SMS рассылками для клиентов',
    'sms.sendNew': 'Отправить новое сообщение',
    'sms.recipient': 'Получатель',
    'sms.recipients': 'Получатели',
    'sms.message': 'Текст сообщения',
    'sms.send': 'Отправить',
    'sms.history': 'История рассылок',
    'sms.sent': 'Отправлено',
    'sms.failed': 'Ошибка',
    'sms.delivered': 'Доставлено',
    'sms.completed': 'Завершено',
    'sms.sending': 'Отправка',
    'sms.draft': 'Черновик',
    'sms.selectClient': 'Выберите клиента',
    'sms.messagePlaceholder': 'Введите текст сообщения...',
    'sms.remaining': 'символов осталось',
    'sms.noCampaigns': 'Нет рассылок',
    'sms.createNew': 'Создайте новую рассылку выше',
    
    // Stats
    'stats.title': 'Статистика',
    'stats.subtitle': 'Общий обзор бизнеса',
    'stats.revenue': 'Доход',
    'stats.revenueByMonth': 'Доход по месяцам',
    'stats.visitsByMonth': 'Визиты по месяцам',
    'stats.byMonth': 'По месяцам',
    'stats.byService': 'По услугам',
    'stats.topClients': 'Топ 5 клиентов',
    'stats.totalPayments': 'Всего платежей',
    'stats.trends': 'Тенденции',
    'stats.export': 'Экспорт данных',
    'stats.noData': 'Нет данных для отображения',
    
    // Partners
    'partners.title': 'Партнёрские предложения',
    'partners.subtitle': 'Откройте для себя рекомендуемые продукты и услуги для вашего бизнеса',
    'partners.noOffers': 'Нет доступных предложений',
    'partners.checkLater': 'Проверьте позже',
    'partners.details': 'Подробнее',
    
    // Common
    'common.loading': 'Загрузка данных...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.close': 'Закрыть',
    'common.back': 'Назад',
    'common.logout': 'Выйти',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.view': 'Просмотр',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.import': 'Импорт',
    'common.refresh': 'Обновить',
    'common.submit': 'Отправить',
    'common.reset': 'Сбросить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.required': 'Обязательное поле',
    'common.optional': 'Необязательно',
    'common.select': 'Выбрать',
    'common.selectAll': 'Выбрать все',
    'common.deselectAll': 'Снять выбор',
    'common.noData': 'Нет данных',
    'common.noResults': 'Нет результатов',
    'common.showing': 'Показано',
    'common.of': 'из',
    'common.items': 'элементов',
    'common.page': 'Страница',
    'common.perPage': 'на странице',
    'common.total': 'Всего',
    'common.actions': 'Действия',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.status': 'Статус',
    'common.active': 'Активен',
    'common.inactive': 'Неактивен',
    'common.enabled': 'Включено',
    'common.disabled': 'Отключено',
    'common.description': 'Описание',
    'common.name': 'Название',
    'common.email': 'Email',
    'common.phone': 'Телефон',
    'common.address': 'Адрес',
    'common.notes': 'Заметки',
    'common.created': 'Создано',
    'common.updated': 'Обновлено',
    'common.createdAt': 'Дата создания',
    'common.updatedAt': 'Дата обновления',
    'common.deleteConfirm': 'Вы уверены, что хотите удалить?',
    'common.cannotUndo': 'Это действие нельзя отменить',
    'common.saving': 'Сохранение...',
    'common.notAvailable': 'Недоступно',
    
    // Error page
    'error.message': 'Что-то пошло не так. Пожалуйста, попробуйте снова или обратитесь в поддержку.',
    'error.retry': 'Попробовать снова',
    'error.backHome': 'Вернуться на главную',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('he')

  useEffect(() => {
    // Load language from localStorage
    const saved = localStorage.getItem('trinity-language') as Language
    if (saved && (saved === 'he' || saved === 'ru')) {
      setLanguageState(saved)
      applyLanguage(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('trinity-language', lang)
    applyLanguage(lang)
  }

  const applyLanguage = (lang: Language) => {
    const dir = lang === 'he' ? 'rtl' : 'ltr'
    document.documentElement.setAttribute('lang', lang)
    document.documentElement.setAttribute('dir', dir)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const dir = language === 'he' ? 'rtl' : 'ltr'

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
