'use client'

import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Language = 'he' | 'ru'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: 'rtl' | 'ltr'
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations: Record<Language, Record<string, string>> = {
  he: {
    // Navigation
    'nav.dashboard': 'דשבורד',
    'nav.clients': 'לקוחות',
    'nav.visits': 'ביקורים',
    'nav.inventory': 'מלאי',
    'nav.payments': 'תשלומים',
    'nav.sms': 'הודעות SMS',
    'nav.stats': 'סטטיסטיקה',
    'nav.partners': 'הצעות שותפים',
    'nav.settings': 'הגדרות',
    'nav.admin': 'פאנל ניהול',
    'nav.darkMode': 'מצב כהה',
    'nav.lightMode': 'מצב בהיר',
    'nav.myProfile': 'הפרופיל שלי',
    'nav.logout': 'יציאה מהמערכת',
    'nav.backToMain': 'חזרה לדשבורד הראשי',
    
    // Admin Navigation
    'admin.dashboard': 'לוח בקרה',
    'admin.organizations': 'ארגונים',
    'admin.billing': 'חיובים',
    'admin.ads': 'פרסום',
    'admin.settings': 'הגדרות',
    
    // Admin Dashboard
    'admin.welcome': 'לוח בקרה - מערכת ניהול',
    'admin.subtitle': 'מבט כללי על המערכת והארגונים',
    'admin.totalOrgs': 'סה״כ ארגונים',
    'admin.activeOrgs': 'ארגונים פעילים',
    'admin.totalUsers': 'סה״כ משתמשים',
    'admin.monthlyRevenue': 'הכנסות חודשיות',
    'admin.recentOrgs': 'ארגונים אחרונים',
    'admin.growth': 'צמיחה',
    'admin.systemHealth': 'מצב המערכת',
    'admin.connected': 'מחובר',
    'admin.notConfigured': 'לא מוגדר',
    'admin.lastUpdate': 'עדכון אחרון',
    'admin.noNewOrgs': 'אין ארגונים חדשים',
    'admin.newOrgsByMonth': 'ארגונים חדשים לפי חודש',
    'admin.loadingChart': 'טוען גרף...',
    
    // Admin Organizations
    'admin.orgs.title': 'ניהול ארגונים',
    'admin.orgs.subtitle': 'צפייה וניהול של כל הארגונים במערכת',
    'admin.orgs.total': 'סה״כ',
    'admin.orgs.organizations': 'ארגונים',
    'admin.orgs.addNew': 'הוסף ארגון חדש',
    'admin.orgs.search': 'חפש לפי שם או אימייל...',
    'admin.orgs.all': 'כל הארגונים',
    'admin.orgs.name': 'שם הארגון',
    'admin.orgs.category': 'קטגוריה',
    'admin.orgs.status': 'סטטוס',
    'admin.orgs.active': 'פעיל',
    'admin.orgs.inactive': 'לא פעיל',
    'admin.orgs.blocked': 'חסום',
    'admin.orgs.suspended': 'מושהה',
    'admin.orgs.users': 'משתמשים',
    'admin.orgs.created': 'תאריך',
    'admin.orgs.plan': 'תוכנית',
    'admin.orgs.basic': 'בסיסי',
    'admin.orgs.pro': 'מקצועי',
    'admin.orgs.premium': 'פרימיום',
    'admin.orgs.enterprise': 'ארגוני',
    'admin.orgs.features': 'פיצ׳רים',
    'admin.orgs.block': 'חסום',
    'admin.orgs.unblock': 'בטל חסימה',
    'admin.orgs.details': 'פרטי ארגון',
    'admin.orgs.view': 'צפייה',
    'admin.orgs.salon': 'מספרה',
    'admin.orgs.carwash': 'שטיפת רכב',
    'admin.orgs.clinic': 'מרפאה',
    'admin.orgs.restaurant': 'מסעדה',
    'admin.orgs.gym': 'חדר כושר',
    'admin.orgs.other': 'אחר',
    'admin.orgs.deleteConfirm': 'האם למחוק משתמש זה?',
    'admin.orgs.noOrgs': 'אין ארגונים במערכת',
    'admin.orgs.addDialog.title': 'הוסף ארגון חדש',
    'admin.orgs.addDialog.desc': 'צור ארגון חדש והקצה בעלים - בחר לקוח קיים או צור חדש',
    'admin.orgs.existingClient': 'לקוח קיים',
    'admin.orgs.newClient': 'לקוח חדש',
    'admin.orgs.selectClient': 'בחר לקוח מהמערכת',
    'admin.orgs.selectClientPlaceholder': 'בחר לקוח',
    'admin.orgs.loadingClients': 'טוען לקוחות...',
    'admin.orgs.noClientsWithEmail': 'אין לקוחות עם אימייל במערכת. עבור ל"לקוח חדש" כדי ליצור.',
    'admin.orgs.autoAssignNote': '💡 אם הלקוח כבר התחבר: יוקצה מיד. אם לא: יוזמן ויוקצה אוטומטית בהתחברות הראשונה.',
    'admin.orgs.orgName': 'שם הארגון',
    'admin.orgs.selectCategory': 'בחר קטגוריה',
    'admin.orgs.selectPlan': 'בחר תוכנית',
    'admin.orgs.clientCreatedNote': '💡 הלקוח יווצר במערכת CRM וישויך לארגון החדש אוטומטית.',
    'admin.orgs.orgDetails': 'פרטי הארגון',
    'admin.orgs.businessName': 'שם העסק',
    'admin.orgs.businessNamePlaceholder': 'שם העסק',
    'admin.orgs.creating': 'יוצר...',
    'admin.orgs.createOrg': 'צור ארגון',
    'admin.orgs.orgDetailsSheet': 'פרטי ארגון',
    'admin.orgs.generalInfo': 'מידע כללי',
    
    // Admin Billing
    'admin.billing.title': 'ניהול חיובים',
    'admin.billing.subtitle': 'מעקב אחר תשלומים ומנויים',
    'admin.billing.totalRevenue': 'סה״כ הכנסות',
    'admin.billing.paidOrgs': 'ארגונים פעילים',
    'admin.billing.overdueOrgs': 'באיחור',
    'admin.billing.trialOrgs': 'תקופת ניסיון',
    'admin.billing.filterByStatus': 'סינון לפי סטטוס',
    'admin.billing.allOrgs': 'כל הארגונים',
    'admin.billing.invoice': 'חשבונית',
    'admin.billing.paid': 'שולם',
    'admin.billing.trial': 'תקופת ניסיון',
    'admin.billing.overdue': 'באיחור',
    'admin.billing.cancelled': 'בוטל',
    'admin.billing.unpaid': 'לא שולם',
    'admin.billing.dueDate': 'תאריך תשלום',
    'admin.billing.total': 'סה״כ',
    'admin.billing.price': 'מחיר',
    'admin.billing.markPaid': 'סמן כשולם',
    'admin.billing.markPaidConfirm': 'האם לסמן תשלום כשולם?',
    'admin.billing.toggleActiveConfirm': 'האם להפעיל/לחסום גישה לארגון זה?',
    'admin.billing.activate': 'הפעל',
    'admin.billing.block': 'חסום',
    'admin.billing.noOrgs': 'אין ארגונים',
    'admin.billing.notSet': 'לא הוגדר',
    'admin.billing.paymentOverdue': 'איחור בתשלום',
    
    // Admin Ads
    'admin.ads.title': 'ניהול פרסומות',
    'admin.ads.subtitle': 'יצירה וניהול של באנרים פרסומיים',
    'admin.ads.totalCampaigns': 'סה״כ קמפיינים',
    'admin.ads.activeCampaigns': 'קמפיינים פעילים',
    'admin.ads.totalImpressions': 'סה״כ צפיות',
    'admin.ads.totalClicks': 'סה״כ קליקים',
    'admin.ads.allCampaigns': 'כל הקמפיינים',
    'admin.ads.addNew': 'הוסף קמפיין',
    'admin.ads.advertiser': 'מפרסם',
    'admin.ads.categories': 'קטגוריות',
    'admin.ads.dates': 'תאריכים',
    'admin.ads.impressions': 'צפיות',
    'admin.ads.clicks': 'קליקים',
    'admin.ads.ctr': 'CTR',
    'admin.ads.active': 'פעיל',
    'admin.ads.inactive': 'לא פעיל',
    'admin.ads.expired': 'פג תוקף',
    'admin.ads.scheduled': 'מתוזמן',
    'admin.ads.edit': 'ערוך',
    'admin.ads.delete': 'מחק',
    'admin.ads.deleteConfirm': 'האם למחוק קמפיין זה?',
    'admin.ads.noCampaigns': 'אין קמפיינים',
    
    // Settings
    'settings.title': 'הגדרות',
    'settings.subtitle': 'נהל את העדפות המערכת שלך',
    'settings.display': 'תצוגה',
    'settings.display.desc': 'צבעים, עיצוב, תבניות',
    'settings.language': 'שפה',
    'settings.language.desc': 'שפת ממשק וכיוון תצוגה',
    'settings.advanced': 'הגדרות נוספות',
    'settings.advanced.desc': 'הגדרות מתקדמות יתווספו בעתיד',
    
    // Display Settings
    'display.title': 'הגדרות תצוגה',
    'display.subtitle': 'התאם את המראה והתחושה של הממשק',
    'display.back': 'חזרה להגדרות',
    'display.colorTheme': 'ערכת נושא חזותית',
    'display.colorTheme.desc': 'בחר את צבע הממשק המועדף עליך',
    'display.darkMode': 'מצב כהה',
    'display.darkMode.desc': 'עבור לממשק כהה (Dark Mode)',
    'display.layout': 'סגנון תצוגה (Layout)',
    'display.layout.desc': 'שנה את אופן התצוגה של הנתונים והכרטיסים',
    'display.customize': 'התאמה מתקדמת',
    'display.customize.desc': 'שליטה מלאה על כל פרט בממשק',
    'display.customize.btn': 'פתח התאמה מתקדמת',
    
    // Language Settings
    'language.title': 'הגדרות שפה',
    'language.subtitle': 'שנה את שפת הממשק וכיוון התצוגה',
    'language.back': 'חזרה להגדרות',
    'language.select': 'בחר שפה',
    'language.select.desc': 'שפת הממשק תשתנה מיד',
    'language.hebrew': 'עברית',
    'language.russian': 'Русский',
    'language.direction': 'כיוון תצוגה',
    'language.rtl': 'ימין לשמאל (RTL)',
    'language.ltr': 'שמאל לימין (LTR)',
    
    // Themes
    'theme.default': 'כחול (ברירת מחדל)',
    'theme.purple': 'סגול',
    'theme.green': 'ירוק',
    'theme.orange': 'כתום',
    'theme.pink': 'ורוד',
    'theme.dark': 'כהה (אינדיגו)',
    
    // Layouts
    'layout.classic': 'קלאסי',
    'layout.classic.desc': 'טבלאות ומינימליזם',
    'layout.modern': 'מודרני',
    'layout.modern.desc': 'כרטיסים גדולים וצללים',
    'layout.compact': 'צפוף',
    'layout.compact.desc': 'יותר מידע במסך',
    
    // Dashboard
    'dashboard.welcome': 'ברוכים הבאים ל-Trinity',
    'dashboard.subtitle': 'מערכת ניהול לקוחות, תשלומים והודעות SMS',
    'dashboard.totalClients': 'סה״כ לקוחות',
    'dashboard.visitsMonth': 'ביקורים החודש',
    'dashboard.revenueMonth': 'הכנסות החודש',
    'dashboard.inactiveClients': 'לקוחות לא פעילים',
    'dashboard.inactiveNote': '30+ ימים ללא ביקור',
    'dashboard.quickActions': 'פעולות מהירות',
    'dashboard.gettingStarted': 'התחלה מהירה',
    'dashboard.step1': 'הוסף לקוחות חדשים בעמוד "לקוחות"',
    'dashboard.step2': 'צור קישורי תשלום בעמוד "תשלומים"',
    'dashboard.step3': 'שלח הודעות SMS ללקוחות בעמוד "הודעות SMS"',
    'dashboard.step4': 'עקוב אחר הנתונים והגרפים בעמוד "סטטיסטיקה"',
    'dashboard.viewFullStats': 'צפה בסטטיסטיקה מלאה',
    
    // Clients
    'clients.title': 'לקוחות',
    'clients.subtitle': 'ניהול לקוחות והיסטוריית ביקורים',
    'clients.addNew': 'הוסף לקוח חדש',
    'clients.search': 'חיפוש לפי שם, טלפון או אימייל',
    'clients.searchPlaceholder': 'חיפוש...',
    'clients.name': 'שם',
    'clients.firstName': 'שם פרטי',
    'clients.lastName': 'שם משפחה',
    'clients.phone': 'טלפון',
    'clients.email': 'אימייל',
    'clients.address': 'כתובת',
    'clients.birthDate': 'תאריך לידה',
    'clients.lastVisit': 'ביקור אחרון',
    'clients.totalSpent': 'סה״כ הוצאות',
    'clients.visits': 'ביקורים',
    'clients.actions': 'פעולות',
    'clients.edit': 'עריכה',
    'clients.delete': 'מחיקה',
    'clients.noClients': 'לא נמצאו לקוחות',
    'clients.addFirst': 'הוסף את הלקוח הראשון שלך',
    'clients.noResults': 'לא נמצאו תוצאות',
    'clients.tryDifferent': 'נסה מילות חיפוש אחרות',
    'clients.details': 'פרטי לקוח',
    'clients.history': 'היסטוריית ביקורים',
    'clients.addVisit': 'הוסף ביקור',
    'clients.date': 'תאריך',
    'clients.service': 'שירות',
    'clients.amount': 'סכום',
    'clients.notes': 'הערות',
    'clients.noOrgFound': 'לא נמצא ארגון למשתמש',
    
    // Visits
    'visits.title': 'ביקורים',
    'visits.subtitle': 'ניהול ביקורים ושירותים',
    'visits.addNew': 'הוסף ביקור חדש',
    'visits.createNew': 'יצירת ביקור חדש',
    'visits.client': 'לקוח',
    'visits.selectClient': 'בחר לקוח',
    'visits.service': 'שירות',
    'visits.selectService': 'בחר שירות',
    'visits.date': 'תאריך',
    'visits.time': 'שעה',
    'visits.duration': 'משך זמן',
    'visits.price': 'מחיר',
    'visits.notes': 'הערות',
    'visits.status': 'סטטוס',
    'visits.scheduled': 'מתוכנן',
    'visits.completed': 'הושלם',
    'visits.cancelled': 'בוטל',
    'visits.noShow': 'לא הגיע',
    'visits.actions': 'פעולות',
    'visits.complete': 'סיים ביקור',
    'visits.cancel': 'בטל ביקור',
    'visits.edit': 'ערוך',
    'visits.delete': 'מחק',
    'visits.noVisits': 'אין ביקורים',
    'visits.createFirst': 'צור את הביקור הראשון',
    'visits.filterByDate': 'סינון לפי תאריך',
    'visits.filterByStatus': 'סינון לפי סטטוס',
    'visits.filterByClient': 'סינון לפי לקוח',
    'visits.month': 'חודש',
    'visits.all': 'הכל',
    'visits.completing': 'משלים...',
    'visits.cancelling': 'מבטל...',
    'visits.creating': 'יוצר...',
    'visits.completeTitle': 'השלמת ביקור',
    'visits.completeDesc': 'בחר את סטטוס הביקור',
    'visits.markCompleted': 'הושלם',
    'visits.markCancelled': 'בוטל',
    'visits.paymentRequired': 'נדרש תשלום',
    'visits.paymentOptional': 'תשלום אופציונלי',
    'visits.completeAndPay': 'השלם ושלם',
    'visits.completeWithoutPayment': 'השלם ללא תשלום',
    'visits.paymentDetails': 'פרטי תשלום',
    'visits.selectPaymentMethod': 'בחר אמצעי תשלום',
    'visits.paymentMethod.cash': 'מזומן',
    'visits.paymentMethod.bit': 'ביט',
    'visits.paymentMethod.credit': 'אשראי (Tranzilla)',
    'visits.paymentMethod.bankTransfer': 'העברה בנקאית',
    'visits.paymentMethod.phoneCredit': 'אשראי טלפוני',
    'visits.paymentMethod.stripe': 'Stripe',
    'visits.processPayment': 'עבד תשלום',
    'visits.processing': 'מעבד...',
    'visits.listView': 'רשימה',
    'visits.calendarView': 'לוח שנה',
    'visits.today': 'היום',
    'visits.week': 'שבוע',
    'visits.previousWeek': 'שבוע קודם',
    'visits.nextWeek': 'שבוע הבא',
    'visits.startVisit': 'התחל ביקור',
    'visits.activeVisit': 'ביקור פעיל',
    'visits.addService': 'הוסף שירות',
    'visits.mainService': 'שירות עיקרי',
    'visits.additionalServices': 'שירותים נוספים',
    'visits.removeService': 'הסר שירות',
    'visits.finishVisit': 'סיים ביקור',
    'visits.cancelVisit': 'בטל ביקור',
    'visits.cancelVisitConfirm': 'האם לבטל את הביקור?',
    'visits.totalPrice': 'סה״כ מחיר',
    'visits.totalDuration': 'סה״כ זמן',
    'visits.elapsedTime': 'זמן שעבר',
    'visits.selectServiceToAdd': 'בחר שירות להוספה',
    'visits.tapToAdd': 'הקש כדי להוסיף ביקור',
    
    // Inventory
    'inventory.title': 'מלאי',
    'inventory.newProduct': 'מוצר חדש',
    'inventory.scanBarcode': 'סריקת ברקוד',
    'inventory.search': 'חיפוש מוצרים',
    'inventory.filterCategory': 'כל הקטגוריות',
    'inventory.filterAll': 'הכל',
    'inventory.filterLowStock': 'מלאי נמוך',
    'inventory.filterOutOfStock': 'אזל',
    'inventory.name': 'שם',
    'inventory.barcode': 'ברקוד',
    'inventory.category': 'קטגוריה',
    'inventory.sellPrice': 'מחיר מכירה',
    'inventory.quantity': 'כמות',
    'inventory.status': 'סטטוס',
    'inventory.inStock': 'במלאי',
    'inventory.lowStock': 'מלאי נמוך',
    'inventory.outOfStock': 'אזל',
    'inventory.purchasePrice': 'מחיר קניה',
    'inventory.minQuantity': 'כמות מינימום',
    'inventory.unit': 'יחידה',
    'inventory.description': 'תיאור',
    'inventory.sku': 'מק"ט',
    'inventory.image': 'תמונה',
    'inventory.active': 'פעיל',
    'inventory.create': 'צור מוצר',
    'inventory.edit': 'ערוך',
    'inventory.delete': 'מחק',
    'inventory.sell': 'מכירה',
    'inventory.addStock': 'הוספת מלאי',
    'inventory.details': 'פרטי מוצר',
    'inventory.transactions': 'היסטוריית תנועות',
    'inventory.noTransactions': 'אין תנועות',
    'inventory.transaction.purchase': 'רכישה',
    'inventory.transaction.sale': 'מכירה',
    'inventory.transaction.return': 'החזרה',
    'inventory.transaction.adjustment': 'תיקון',
    'inventory.transaction.writeOff': 'מחיקה',
    'inventory.sellDialog.title': 'מכירת מוצר',
    'inventory.sellDialog.quantity': 'כמות',
    'inventory.sellDialog.price': 'מחיר ליחידה',
    'inventory.sellDialog.client': 'לקוח (אופציונלי)',
    'inventory.sellDialog.total': 'סה"כ',
    'inventory.sellDialog.confirm': 'אשר מכירה',
    'inventory.addStockDialog.title': 'הוספת מלאי',
    'inventory.addStockDialog.quantity': 'כמות',
    'inventory.addStockDialog.purchasePrice': 'מחיר קניה (אופציונלי)',
    'inventory.addStockDialog.notes': 'הערות',
    'inventory.addStockDialog.confirm': 'הוסף למלאי',
    'inventory.scanner.title': 'סריקת ברקוד',
    'inventory.scanner.switchCamera': 'החלף מצלמה',
    'inventory.scanner.manualEntry': 'הקלד ידנית',
    'inventory.scanner.cameraError': 'שגיאת גישה למצלמה',
    'inventory.unit.piece': 'יחידה',
    'inventory.unit.kg': 'קילוגרם',
    'inventory.unit.liter': 'ליטר',
    'inventory.unit.package': 'אריזה',
    'inventory.category.beauty': 'קוסמטיקה',
    'inventory.category.hair': 'שיער',
    'inventory.category.nails': 'ציפורניים',
    'inventory.category.equipment': 'ציוד',
    'inventory.category.other': 'אחר',
    'inventory.emptyState': 'אין מוצרים במלאי',
    'inventory.emptyState.desc': 'התחל להוסיף מוצרים למלאי שלך',
    'inventory.quickSale': 'מכירה מהירה',
    'inventory.quickSale.title': 'מכירה מהירה',
    'inventory.quickSale.addProduct': 'הוסף מוצר',
    'inventory.quickSale.cart': 'עגלה',
    'inventory.quickSale.empty': 'העגלה ריקה',
    'inventory.quickSale.complete': 'השלם מכירה',
    'inventory.return': 'החזרת מוצר',
    'inventory.return.title': 'החזרת מוצר',
    'inventory.return.product': 'מוצר',
    'inventory.return.quantity': 'כמות החזרה',
    'inventory.return.reason': 'סיבה',
    'inventory.return.confirm': 'אשר החזרה',
    'inventory.lowStockAlert': 'מלאי נמוך',
    'inventory.lowStockAlert.desc': 'יש {count} מוצרים עם מלאי נמוך',
    'inventory.lowStockAlert.view': 'צפה במוצרים',
    
    // Services Management
    'services.title': 'שירותים',
    'services.newService': 'הוסף שירות',
    'services.editService': 'ערוך שירות',
    'services.name': 'שם השירות',
    'services.nameRu': 'שם השירות (רוסית)',
    'services.namePlaceholder': 'למשל: תספורת גברים',
    'services.nameRuPlaceholder': 'Например: Мужская стрижка',
    'services.price': 'מחיר',
    'services.duration': 'משך זמן',
    'services.color': 'צבע',
    'services.description': 'תיאור',
    'services.descriptionRu': 'תיאור (רוסית)',
    'services.descriptionPlaceholder': 'תיאור קצר של השירות...',
    'services.descriptionRuPlaceholder': 'Краткое описание услуги...',
    'services.edit': 'ערוך',
    'services.delete': 'מחק',
    'services.created': 'השירות נוצר בהצלחה',
    'services.updated': 'השירות עודכן בהצלחה',
    'services.deleted': 'השירות נמחק בהצלחה',
    'services.deleteConfirm': 'מחיקת שירות',
    'services.deleteConfirmMessage': 'האם למחוק את השירות "{name}"? פעולה זו לא ניתנת לביטול.',
    'services.searchPlaceholder': 'חפש שירות...',
    'services.noResultsFound': 'לא נמצאו תוצאות',
    'services.noServicesYet': 'עדיין אין שירותים במערכת',
    'services.createFirst': 'צור שירות ראשון',
    'services.emptyState': 'אין שירותים',
    'services.emptyState.desc': 'התחל להוסיף שירותים למערכת',
    'services.errors.nameRequired': 'שם השירות הוא שדה חובה',
    'services.errors.priceInvalid': 'המחיר חייב להיות חיובי',
    'services.errors.durationInvalid': 'משך הזמן חייב להיות לפחות דקה אחת',
    
    // Care Instructions
    'careInstructions.title': 'הוראות טיפול',
    'careInstructions.description': 'נהל הוראות טיפול ללקוחות לאחר השירותים',
    'careInstructions.newInstruction': 'הוסף הוראה',
    'careInstructions.editInstruction': 'ערוך הוראה',
    'careInstructions.instructionTitle': 'כותרת',
    'careInstructions.instructionTitleRu': 'כותרת (רוסית)',
    'careInstructions.instructionContent': 'תוכן ההוראה',
    'careInstructions.instructionContentRu': 'תוכן (רוסית)',
    'careInstructions.selectService': 'בחר שירות',
    'careInstructions.noService': 'כללי (לכל השירותים)',
    'careInstructions.created': 'ההוראה נוצרה בהצלחה',
    'careInstructions.updated': 'ההוראה עודכנה בהצלחה',
    'careInstructions.deleted': 'ההוראה נמחקה בהצלחה',
    'careInstructions.deleteConfirm': 'למחוק הוראה זו?',
    'careInstructions.sendInstructions': 'שלח הוראות טיפול',
    'careInstructions.downloadPDF': 'הורד PDF',
    'careInstructions.sendWhatsApp': 'שלח בוואטסאפ',
    'careInstructions.noInstructions': 'אין הוראות טיפול',
    'careInstructions.noInstructionsForService': 'אין הוראות טיפול לשירות זה',
    
    // Settings - Service Colors
    'settings.serviceColors': 'צבעי שירותים',
    'settings.serviceColors.desc': 'התאם צבעים לכל סוג שירות',
    'settings.serviceColors.save': 'שמור צבעים',
    
    // Services (for visits)
    'service.haircut': 'תספורת',
    'service.coloring': 'צבע',
    'service.smoothing': 'החלקה',
    'service.facial': 'טיפול פנים',
    'service.manicure': 'מניקור',
    'service.pedicure': 'פדיקור',
    'service.haircutColoring': 'תספורת + צבע',
    'service.hairTreatment': 'טיפול שיער',
    'service.consultation': 'ייעוץ',
    'service.meeting': 'פגישה',
    'service.advertising': 'פרסום',
    'service.other': 'אחר',
    
    // Duration options
    'duration.30min': '30 דקות',
    'duration.45min': '45 דקות',
    'duration.60min': '60 דקות (שעה)',
    'duration.90min': '90 דקות (שעה וחצי)',
    'duration.120min': '120 דקות (שעתיים)',
    
    // Payments
    'payments.title': 'תשלומים',
    'payments.subtitle': 'ניהול תשלומים והכנסות',
    'payments.addNew': 'הוסף תשלום',
    'payments.createLink': 'צור קישור לתשלום',
    'payments.cashPayment': 'מזומן',
    'payments.cashPaymentSuccess': 'התשלום נרשם בהצלחה',
    'payments.createFirst': 'צור קישור לתשלום ראשון',
    'payments.client': 'לקוח',
    'payments.selectClient': 'בחר לקוח',
    'payments.amount': 'סכום',
    'payments.amountPlaceholder': '100.00',
    'payments.description': 'תיאור',
    'payments.descriptionPlaceholder': 'תיאור התשלום (אופציונלי)',
    'payments.status': 'סטטוס',
    'payments.paid': 'שולם',
    'payments.pending': 'ממתין',
    'payments.failed': 'נכשל',
    'payments.refunded': 'הוחזר',
    'payments.cancelled': 'בוטל',
    'payments.method': 'אמצעי תשלום',
    'payments.cash': 'מזומן',
    'payments.card': 'כרטיס אשראי',
    'payments.bankTransfer': 'העברה בנקאית',
    'payments.total': 'סה״כ',
    'payments.filter': 'סינון',
    'payments.all': 'הכל',
    'payments.fromDate': 'מתאריך',
    'payments.toDate': 'עד תאריך',
    'payments.totalMonth': 'סך התשלומים החודש',
    'payments.successfulTransactions': 'עסקאות מוצלחות',
    'payments.avgTransaction': 'ממוצע לעסקה',
    'payments.noPayments': 'אין תשלומים',
    'payments.unknown': 'לא ידוע',
    'payments.copyLink': 'העתק קישור',
    'payments.openLink': 'פתח קישור',
    'payments.transactionId': 'מזהה עסקה',
    'payments.linkCopied': 'הקישור הועתק ללוח',
    'payments.successMessage': 'קישור התשלום נוצר בהצלחה!',
    'payments.sendLinkToClient': 'שלח את הקישור ללקוח כדי שיוכל לשלם באופן מאובטח',
    'payments.failedMessage': 'התשלום נכשל',
    'payments.creating': 'יוצר קישור...',
    'payments.paymentSuccess': 'התשלום בוצע בהצלחה!',
    'payments.paymentCanceled': 'התשלום בוטל',
    'payments.filterByMethod': 'סינון לפי אמצעי תשלום',
    'payments.filterByStatus': 'סינון לפי סטטוס',
    'payments.filterByDate': 'סינון לפי תאריך',
    'payments.filterByClient': 'סינון לפי לקוח',
    'payments.method.cash': 'מזומן',
    'payments.method.bit': 'ביט',
    'payments.method.credit': 'אשראי',
    'payments.method.stripe': 'Stripe',
    'payments.method.bankTransfer': 'העברה בנקאית',
    'payments.method.phoneCredit': 'אשראי טלפוני',
    
    // Subscriptions
    'subscriptions.create': 'צור מנוי',
    'subscriptions.createNew': 'יצירת מנוי חדש',
    'subscriptions.selectClient': 'בחר לקוח',
    'subscriptions.amount': 'סכום',
    'subscriptions.amountPlaceholder': 'הכנס סכום',
    'subscriptions.interval': 'תדירות תשלום',
    'subscriptions.monthly': 'חודשי',
    'subscriptions.weekly': 'שבועי',
    'subscriptions.yearly': 'שנתי',
    'subscriptions.creating': 'יוצר...',
    
    // SMS
    'sms.title': 'הודעות SMS',
    'sms.subtitle': 'נהל רסלות SMS ללקוחות',
    'sms.sendNew': 'שלח הודעה חדשה',
    'sms.newMessage': 'הודעה חדשה',
    'sms.campaignName': 'שם הקמפיין',
    'sms.campaignNamePlaceholder': 'לדוגמה: תזכורת לביקור',
    'sms.messageContent': 'תוכן ההודעה',
    'sms.messageContentPlaceholder': 'שלום! תזכורת ל תזכורת לביקור שלך...',
    'sms.sendingType': 'סוג השליחה',
    'sms.sendToAll': 'שלח לכלל',
    'sms.sendToAllDesc': 'שלח לכל הלקוחות במערכת',
    'sms.sendToOne': 'שלח לקוח אחד',
    'sms.sendToOneDesc': 'בחר לקוח ספציפי',
    'sms.sendToInactive': 'לקוחות לא פעילים',
    'sms.sendToInactiveDesc': 'לקוחות שלא ביקרו לאחרונה',
    'sms.messageHistory': 'הודעה נשלחה ל-{count} מקבלים',
    'sms.recipient': 'נמען',
    'sms.recipients': 'מקבלים',
    'sms.message': 'תוכן ההודעה',
    'sms.send': 'שלח',
    'sms.history': 'היסטוריית רסלות',
    'sms.sent': 'נשלחו',
    'sms.failed': 'נכשלו',
    'sms.delivered': 'נמסר',
    'sms.completed': 'הושלם',
    'sms.sending': 'שולח',
    'sms.draft': 'טיוטה',
    'sms.selectClient': 'בחר לקוח',
    'sms.messagePlaceholder': 'הקלד את ההודעה כאן...',
    'sms.remaining': 'תווים נותרים',
    'sms.charactersCount': '0 תווים (0 SMS)',
    'sms.singleMessage': 'הודעה בודדת',
    'sms.multiPartMessage': 'הודעה מרובת חלקים',
    'sms.sendNow': 'שלח עכשיו',
    'sms.confirmSend': 'אישור שליחה',
    'sms.confirmMessage': 'האם אתה בטוח שברצונך לשלוח את ההודעה ל-{count} מקבלים?',
    'sms.multiPartWarning': 'שים לב: כל הודעה תישלח ב-{parts} חלקים',
    'sms.willBeSentTo': 'הודעה תישלח ל-{count} מקבלים',
    'sms.costPerMessage': 'כל הודעה תישלח ב-{parts} חלקים (עלות: {parts}x)',
    'sms.inactiveDays': 'לא ביקרו במשך',
    'sms.days': 'ימים',
    'sms.noCampaigns': 'אין רסלות',
    'sms.createNew': 'צור רסלה חדשה למעלה',
    
    // Stats
    'stats.title': 'סטטיסטיקה',
    'stats.subtitle': 'מבט כללי על העסק',
    'stats.revenue': 'הכנסות',
    'stats.revenueByMonth': 'הכנסות לפי חודש',
    'stats.visitsByMonth': 'ביקורים לפי חודש',
    'stats.byMonth': 'לפי חודש',
    'stats.byService': 'לפי שירות',
    'stats.topClients': '5 הלקוחות המובילים',
    'stats.totalPayments': 'סה״כ תשלומים',
    'stats.trends': 'מגמות',
    'stats.export': 'ייצוא נתונים',
    'stats.noData': 'אין נתונים להצגה',
    
    // Analytics
    'analytics.title': 'דוחות ואנליטיקה',
    'analytics.subtitle': 'ניתוח מעמיק של הנתונים העסקיים',
    'analytics.paymentMethods': 'התפלגות אמצעי תשלום',
    'analytics.revenueOverTime': 'הכנסות לאורך זמן',
    'analytics.totalRevenue': 'סה״כ הכנסות',
    'analytics.avgTransaction': 'ממוצע לעסקה',
    'analytics.totalTransactions': 'סה״כ עסקאות',
    'analytics.period': 'תקופה',
    'analytics.daily': 'יומי',
    'analytics.weekly': 'שבועי',
    'analytics.monthly': 'חודשי',
    'analytics.filterByMethod': 'סינון לפי אמצעי תשלום',
    'analytics.allMethods': 'כל האמצעים',
    
    // Partners
    'partners.title': 'הצעות שותפים',
    'partners.subtitle': 'גלה מוצרים ושירותים מומלצים לעסק שלך',
    'partners.noOffers': 'אין הצעות זמינות כרגע',
    'partners.checkLater': 'בדוק שוב מאוחר יותר',
    'partners.details': 'לפרטים',
    
    // Common
    'common.loading': 'טוען נתונים...',
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.minutes': 'דקות',
    'common.close': 'סגור',
    'common.back': 'חזרה',
    'common.logout': 'התנתק',
    'common.add': 'הוסף',
    'common.edit': 'ערוך',
    'common.delete': 'מחק',
    'common.view': 'צפה',
    'common.search': 'חיפוש',
    'common.filter': 'סנן',
    'common.export': 'ייצא',
    'common.import': 'ייבא',
    'common.refresh': 'רענן',
    'common.submit': 'שלח',
    'common.reset': 'אפס',
    'common.confirm': 'אישור',
    'common.yes': 'כן',
    'common.no': 'לא',
    'common.ok': 'אישור',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.warning': 'אזהרה',
    'common.info': 'מידע',
    'common.required': 'שדה חובה',
    'common.optional': 'אופציונלי',
    'common.select': 'בחר',
    'common.selectAll': 'בחר הכל',
    'common.deselectAll': 'בטל בחירת הכל',
    'common.noData': 'אין נתונים',
    'common.noResults': 'אין תוצאות',
    'common.showing': 'מציג',
    'common.of': 'מתוך',
    'common.items': 'פריטים',
    'common.page': 'עמוד',
    'common.perPage': 'לעמוד',
    'common.total': 'סה״כ',
    'common.actions': 'פעולות',
    'common.date': 'תאריך',
    'common.time': 'שעה',
    'common.status': 'סטטוס',
    'common.active': 'פעיל',
    'common.inactive': 'לא פעיל',
    'common.enabled': 'מופעל',
    'common.disabled': 'מושבת',
    'common.description': 'תיאור',
    'common.name': 'שם',
    'common.email': 'אימייל',
    'common.phone': 'טלפון',
    'common.address': 'כתובת',
    'common.notes': 'הערות',
    'common.created': 'נוצר',
    'common.updated': 'עודכן',
    'common.createdAt': 'תאריך יצירה',
    'common.updatedAt': 'תאריך עדכון',
    'common.deleteConfirm': 'האם אתה בטוח שברצונך למחוק?',
    'common.cannotUndo': 'לא ניתן לבטל פעולה זו',
    'common.saving': 'שומר...',
    'common.deleting': 'מוחק...',
    'common.notAvailable': 'לא זמין',
    
    // Error page
    'error.message': 'משהו השתבש. אנא נסה שוב או פנה לתמיכה.',
    'error.retry': 'נסה שוב',
    'error.backHome': 'חזור לדף הבית',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Дашборд',
    'nav.clients': 'Клиенты',
    'nav.visits': 'Визиты',
    'nav.inventory': 'Склад',
    'nav.payments': 'Платежи',
    'nav.sms': 'SMS сообщения',
    'nav.stats': 'Статистика',
    'nav.partners': 'Партнёрские предложения',
    'nav.settings': 'Настройки',
    'nav.admin': 'Панель управления',
    'nav.darkMode': 'Тёмная тема',
    'nav.lightMode': 'Светлая тема',
    'nav.myProfile': 'Мой профиль',
    'nav.logout': 'Выйти из системы',
    'nav.backToMain': 'Вернуться в главный дашборд',
    
    // Admin Navigation
    'admin.dashboard': 'Панель управления',
    'admin.organizations': 'Организации',
    'admin.billing': 'Оплата',
    'admin.ads': 'Реклама',
    'admin.settings': 'Настройки',
    
    // Admin Dashboard
    'admin.welcome': 'Панель управления - Система управления',
    'admin.subtitle': 'Общий обзор системы и организаций',
    'admin.totalOrgs': 'Всего организаций',
    'admin.activeOrgs': 'Активных организаций',
    'admin.totalUsers': 'Всего пользователей',
    'admin.monthlyRevenue': 'Месячный доход',
    'admin.recentOrgs': 'Последние организации',
    'admin.growth': 'Рост',
    'admin.systemHealth': 'Состояние системы',
    'admin.connected': 'Подключено',
    'admin.notConfigured': 'Не настроено',
    'admin.lastUpdate': 'Последнее обновление',
    'admin.noNewOrgs': 'Нет новых организаций',
    'admin.newOrgsByMonth': 'Новые организации по месяцам',
    'admin.loadingChart': 'Загрузка графика...',
    
    // Admin Organizations
    'admin.orgs.title': 'Управление организациями',
    'admin.orgs.subtitle': 'Просмотр и управление всеми организациями в системе',
    'admin.orgs.total': 'Всего',
    'admin.orgs.organizations': 'организаций',
    'admin.orgs.addNew': 'Добавить новую организацию',
    'admin.orgs.search': 'Поиск по названию или email...',
    'admin.orgs.all': 'Все организации',
    'admin.orgs.name': 'Название организации',
    'admin.orgs.category': 'Категория',
    'admin.orgs.status': 'Статус',
    'admin.orgs.active': 'Активна',
    'admin.orgs.inactive': 'Неактивна',
    'admin.orgs.blocked': 'Заблокирована',
    'admin.orgs.suspended': 'Приостановлена',
    'admin.orgs.users': 'Пользователи',
    'admin.orgs.created': 'Дата',
    'admin.orgs.plan': 'План',
    'admin.orgs.basic': 'Базовый',
    'admin.orgs.pro': 'Профессиональный',
    'admin.orgs.premium': 'Премиум',
    'admin.orgs.enterprise': 'Корпоративный',
    'admin.orgs.features': 'Возможности',
    'admin.orgs.block': 'Заблокировать',
    'admin.orgs.unblock': 'Разблокировать',
    'admin.orgs.details': 'Детали организации',
    'admin.orgs.view': 'Просмотр',
    'admin.orgs.salon': 'Салон',
    'admin.orgs.carwash': 'Автомойка',
    'admin.orgs.clinic': 'Клиника',
    'admin.orgs.restaurant': 'Ресторан',
    'admin.orgs.gym': 'Фитнес-зал',
    'admin.orgs.other': 'Другое',
    'admin.orgs.deleteConfirm': 'Удалить этого пользователя?',
    'admin.orgs.noOrgs': 'Нет организаций в системе',
    'admin.orgs.addDialog.title': 'Добавить новую организацию',
    'admin.orgs.addDialog.desc': 'Создайте новую организацию и назначьте владельца - выберите существующего клиента или создайте нового',
    'admin.orgs.existingClient': 'Существующий клиент',
    'admin.orgs.newClient': 'Новый клиент',
    'admin.orgs.selectClient': 'Выберите клиента из системы',
    'admin.orgs.selectClientPlaceholder': 'Выберите клиента',
    'admin.orgs.loadingClients': 'Загрузка клиентов...',
    'admin.orgs.noClientsWithEmail': 'Нет клиентов с email в системе. Перейдите в "Новый клиент" для создания.',
    'admin.orgs.autoAssignNote': '💡 Если клиент уже вошёл: назначится сразу. Если нет: будет приглашён и назначится автоматически при первом входе.',
    'admin.orgs.orgName': 'Название организации',
    'admin.orgs.selectCategory': 'Выберите категорию',
    'admin.orgs.selectPlan': 'Выберите план',
    'admin.orgs.clientCreatedNote': '💡 Клиент будет создан в CRM системе и автоматически привязан к новой организации.',
    'admin.orgs.orgDetails': 'Детали организации',
    'admin.orgs.businessName': 'Название бизнеса',
    'admin.orgs.businessNamePlaceholder': 'Название бизнеса',
    'admin.orgs.creating': 'Создание...',
    'admin.orgs.createOrg': 'Создать организацию',
    'admin.orgs.orgDetailsSheet': 'Детали организации',
    'admin.orgs.generalInfo': 'Общая информация',
    
    // Admin Billing
    'admin.billing.title': 'Управление платежами',
    'admin.billing.subtitle': 'Отслеживание платежей и подписок',
    'admin.billing.totalRevenue': 'Всего доход',
    'admin.billing.paidOrgs': 'Активных организаций',
    'admin.billing.overdueOrgs': 'Просрочено',
    'admin.billing.trialOrgs': 'Пробный период',
    'admin.billing.filterByStatus': 'Фильтр по статусу',
    'admin.billing.allOrgs': 'Все организации',
    'admin.billing.invoice': 'Счёт',
    'admin.billing.paid': 'Оплачено',
    'admin.billing.trial': 'Пробный период',
    'admin.billing.overdue': 'Просрочено',
    'admin.billing.cancelled': 'Отменено',
    'admin.billing.unpaid': 'Не оплачено',
    'admin.billing.dueDate': 'Срок оплаты',
    'admin.billing.total': 'Итого',
    'admin.billing.price': 'Цена',
    'admin.billing.markPaid': 'Отметить как оплачено',
    'admin.billing.markPaidConfirm': 'Отметить платёж как оплаченный?',
    'admin.billing.toggleActiveConfirm': 'Активировать/заблокировать доступ для этой организации?',
    'admin.billing.activate': 'Активировать',
    'admin.billing.block': 'Заблокировать',
    'admin.billing.noOrgs': 'Нет организаций',
    'admin.billing.notSet': 'Не установлено',
    'admin.billing.paymentOverdue': 'Просрочка платежа',
    
    // Admin Ads
    'admin.ads.title': 'Управление рекламой',
    'admin.ads.subtitle': 'Создание и управление рекламными баннерами',
    'admin.ads.totalCampaigns': 'Всего кампаний',
    'admin.ads.activeCampaigns': 'Активных кампаний',
    'admin.ads.totalImpressions': 'Всего просмотров',
    'admin.ads.totalClicks': 'Всего кликов',
    'admin.ads.allCampaigns': 'Все кампании',
    'admin.ads.addNew': 'Добавить кампанию',
    'admin.ads.advertiser': 'Рекламодатель',
    'admin.ads.categories': 'Категории',
    'admin.ads.dates': 'Даты',
    'admin.ads.impressions': 'Просмотры',
    'admin.ads.clicks': 'Клики',
    'admin.ads.ctr': 'CTR',
    'admin.ads.active': 'Активна',
    'admin.ads.inactive': 'Неактивна',
    'admin.ads.expired': 'Истёк',
    'admin.ads.scheduled': 'Запланирована',
    'admin.ads.edit': 'Редактировать',
    'admin.ads.delete': 'Удалить',
    'admin.ads.deleteConfirm': 'Удалить эту кампанию?',
    'admin.ads.noCampaigns': 'Нет кампаний',
    
    // Settings
    'settings.title': 'Настройки',
    'settings.subtitle': 'Управляйте настройками системы',
    'settings.display': 'Внешний вид',
    'settings.display.desc': 'Цвета, дизайн, темы',
    'settings.language': 'Язык',
    'settings.language.desc': 'Язык интерфейса и направление текста',
    'settings.advanced': 'Дополнительные настройки',
    'settings.advanced.desc': 'Будут добавлены в будущем',
    
    // Display Settings
    'display.title': 'Настройки внешнего вида',
    'display.subtitle': 'Настройте внешний вид интерфейса',
    'display.back': 'Назад к настройкам',
    'display.colorTheme': 'Цветовая тема',
    'display.colorTheme.desc': 'Выберите предпочитаемый цвет интерфейса',
    'display.darkMode': 'Тёмная тема',
    'display.darkMode.desc': 'Переключить на тёмный интерфейс (Dark Mode)',
    'display.layout': 'Стиль отображения (Layout)',
    'display.layout.desc': 'Измените способ отображения данных и карточек',
    'display.customize': 'Расширенная настройка',
    'display.customize.desc': 'Полный контроль над каждой деталью интерфейса',
    'display.customize.btn': 'Открыть расширенные настройки',
    
    // Language Settings
    'language.title': 'Настройки языка',
    'language.subtitle': 'Измените язык интерфейса и направление отображения',
    'language.back': 'Назад к настройкам',
    'language.select': 'Выберите язык',
    'language.select.desc': 'Интерфейс сразу переключится на выбранный язык',
    'language.hebrew': 'עברית',
    'language.russian': 'Русский',
    'language.direction': 'Направление текста',
    'language.rtl': 'Справа налево (RTL)',
    'language.ltr': 'Слева направо (LTR)',
    
    // Themes
    'theme.default': 'Синий (по умолчанию)',
    'theme.purple': 'Фиолетовый',
    'theme.green': 'Зелёный',
    'theme.orange': 'Оранжевый',
    'theme.pink': 'Розовый',
    'theme.dark': 'Тёмный (индиго)',
    
    // Layouts
    'layout.classic': 'Классический',
    'layout.classic.desc': 'Таблицы и минимализм',
    'layout.modern': 'Современный',
    'layout.modern.desc': 'Большие карточки с тенями',
    'layout.compact': 'Компактный',
    'layout.compact.desc': 'Больше информации на экране',
    
    // Dashboard
    'dashboard.welcome': 'Добро пожаловать в Trinity',
    'dashboard.subtitle': 'Система управления клиентами, платежами и SMS',
    'dashboard.totalClients': 'Всего клиентов',
    'dashboard.visitsMonth': 'Визиты за месяц',
    'dashboard.revenueMonth': 'Доход за месяц',
    'dashboard.inactiveClients': 'Неактивные клиенты',
    'dashboard.inactiveNote': '30+ дней без визита',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.gettingStarted': 'Быстрый старт',
    'dashboard.step1': 'Добавьте новых клиентов на странице "Клиенты"',
    'dashboard.step2': 'Создайте ссылки для оплаты на странице "Платежи"',
    'dashboard.step3': 'Отправляйте SMS клиентам на странице "SMS сообщения"',
    'dashboard.step4': 'Отслеживайте данные и графики на странице "Статистика"',
    'dashboard.viewFullStats': 'Посмотреть полную статистику',
    
    // Clients
    'clients.title': 'Клиенты',
    'clients.subtitle': 'Управление клиентами и история визитов',
    'clients.addNew': 'Добавить нового клиента',
    'clients.search': 'Поиск по имени, телефону или email',
    'clients.searchPlaceholder': 'Поиск...',
    'clients.name': 'Имя',
    'clients.firstName': 'Имя',
    'clients.lastName': 'Фамилия',
    'clients.phone': 'Телефон',
    'clients.email': 'Email',
    'clients.address': 'Адрес',
    'clients.birthDate': 'Дата рождения',
    'clients.lastVisit': 'Последний визит',
    'clients.totalSpent': 'Всего потрачено',
    'clients.visits': 'Визиты',
    'clients.actions': 'Действия',
    'clients.edit': 'Редактировать',
    'clients.delete': 'Удалить',
    'clients.noClients': 'Клиенты не найдены',
    'clients.addFirst': 'Добавьте вашего первого клиента',
    'clients.noResults': 'Нет результатов',
    'clients.tryDifferent': 'Попробуйте другие ключевые слова',
    'clients.details': 'Детали клиента',
    'clients.history': 'История визитов',
    'clients.addVisit': 'Добавить визит',
    'clients.date': 'Дата',
    'clients.service': 'Услуга',
    'clients.amount': 'Сумма',
    'clients.notes': 'Заметки',
    'clients.noOrgFound': 'Организация для пользователя не найдена',
    
    // Visits
    'visits.title': 'Визиты',
    'visits.subtitle': 'Управление визитами и услугами',
    'visits.addNew': 'Добавить новый визит',
    'visits.createNew': 'Создание нового визита',
    'visits.client': 'Клиент',
    'visits.selectClient': 'Выберите клиента',
    'visits.service': 'Услуга',
    'visits.selectService': 'Выберите услугу',
    'visits.date': 'Дата',
    'visits.time': 'Время',
    'visits.duration': 'Продолжительность',
    'visits.price': 'Цена',
    'visits.notes': 'Заметки',
    'visits.status': 'Статус',
    'visits.scheduled': 'Запланирован',
    'visits.completed': 'Завершён',
    'visits.cancelled': 'Отменён',
    'visits.noShow': 'Не пришёл',
    'visits.actions': 'Действия',
    'visits.complete': 'Завершить визит',
    'visits.cancel': 'Отменить визит',
    'visits.edit': 'Редактировать',
    'visits.delete': 'Удалить',
    'visits.noVisits': 'Нет визитов',
    'visits.createFirst': 'Создайте первый визит',
    'visits.filterByDate': 'Фильтр по дате',
    'visits.filterByStatus': 'Фильтр по статусу',
    'visits.filterByClient': 'Фильтр по клиенту',
    'visits.month': 'Месяц',
    'visits.all': 'Всё',
    'visits.completing': 'Завершение...',
    'visits.cancelling': 'Отмена...',
    'visits.creating': 'Создание...',
    'visits.completeTitle': 'Завершение визита',
    'visits.completeDesc': 'Выберите статус визита',
    'visits.markCompleted': 'Завершён',
    'visits.markCancelled': 'Отменён',
    'visits.paymentRequired': 'Требуется оплата',
    'visits.paymentOptional': 'Оплата необязательна',
    'visits.completeAndPay': 'Завершить и оплатить',
    'visits.completeWithoutPayment': 'Завершить без оплаты',
    'visits.paymentDetails': 'Детали оплаты',
    'visits.selectPaymentMethod': 'Выберите способ оплаты',
    'visits.paymentMethod.cash': 'Наличные',
    'visits.paymentMethod.bit': 'Bit',
    'visits.paymentMethod.credit': 'Кредитная карта (Tranzilla)',
    'visits.paymentMethod.bankTransfer': 'Банковский перевод',
    'visits.paymentMethod.phoneCredit': 'Телефонная оплата',
    'visits.paymentMethod.stripe': 'Stripe',
    'visits.processPayment': 'Обработать платёж',
    'visits.processing': 'Обработка...',
    'visits.listView': 'Список',
    'visits.calendarView': 'Календарь',
    'visits.today': 'Сегодня',
    'visits.week': 'Неделя',
    'visits.previousWeek': 'Предыдущая неделя',
    'visits.nextWeek': 'Следующая неделя',
    'visits.startVisit': 'Начать визит',
    'visits.activeVisit': 'Активный визит',
    'visits.addService': 'Добавить услугу',
    'visits.mainService': 'Основная услуга',
    'visits.additionalServices': 'Дополнительные услуги',
    'visits.removeService': 'Удалить услугу',
    'visits.finishVisit': 'Завершить визит',
    'visits.cancelVisit': 'Отменить визит',
    'visits.cancelVisitConfirm': 'Отменить этот визит?',
    'visits.totalPrice': 'Итого цена',
    'visits.totalDuration': 'Итого время',
    'visits.elapsedTime': 'Прошло времени',
    'visits.selectServiceToAdd': 'Выберите услугу для добавления',
    'visits.tapToAdd': 'Нажмите чтобы добавить визит',
    
    // Inventory
    'inventory.title': 'Склад',
    'inventory.newProduct': 'Новый товар',
    'inventory.scanBarcode': 'Сканер',
    'inventory.search': 'Поиск товаров',
    'inventory.filterCategory': 'Все категории',
    'inventory.filterAll': 'Все',
    'inventory.filterLowStock': 'Мало',
    'inventory.filterOutOfStock': 'Нет',
    'inventory.name': 'Название',
    'inventory.barcode': 'Штрих-код',
    'inventory.category': 'Категория',
    'inventory.sellPrice': 'Цена продажи',
    'inventory.quantity': 'Количество',
    'inventory.status': 'Статус',
    'inventory.inStock': 'В наличии',
    'inventory.lowStock': 'Мало',
    'inventory.outOfStock': 'Нет',
    'inventory.purchasePrice': 'Цена закупки',
    'inventory.minQuantity': 'Минимум',
    'inventory.unit': 'Единица',
    'inventory.description': 'Описание',
    'inventory.sku': 'Артикул',
    'inventory.image': 'Изображение',
    'inventory.active': 'Активен',
    'inventory.create': 'Создать товар',
    'inventory.edit': 'Редактировать',
    'inventory.delete': 'Удалить',
    'inventory.sell': 'Продажа',
    'inventory.addStock': 'Добавить на склад',
    'inventory.details': 'Детали товара',
    'inventory.transactions': 'История движений',
    'inventory.noTransactions': 'Нет операций',
    'inventory.transaction.purchase': 'Закупка',
    'inventory.transaction.sale': 'Продажа',
    'inventory.transaction.return': 'Возврат',
    'inventory.transaction.adjustment': 'Корректировка',
    'inventory.transaction.writeOff': 'Списание',
    'inventory.sellDialog.title': 'Продажа товара',
    'inventory.sellDialog.quantity': 'Количество',
    'inventory.sellDialog.price': 'Цена за единицу',
    'inventory.sellDialog.client': 'Клиент (опционально)',
    'inventory.sellDialog.total': 'Итого',
    'inventory.sellDialog.confirm': 'Подтвердить продажу',
    'inventory.addStockDialog.title': 'Добавление на склад',
    'inventory.addStockDialog.quantity': 'Количество',
    'inventory.addStockDialog.purchasePrice': 'Цена закупки (опционально)',
    'inventory.addStockDialog.notes': 'Примечания',
    'inventory.addStockDialog.confirm': 'Добавить на склад',
    'inventory.scanner.title': 'Сканирование штрих-кода',
    'inventory.scanner.switchCamera': 'Сменить камеру',
    'inventory.scanner.manualEntry': 'Ввести вручную',
    'inventory.scanner.cameraError': 'Ошибка доступа к камере',
    'inventory.unit.piece': 'Штука',
    'inventory.unit.kg': 'Килограмм',
    'inventory.unit.liter': 'Литр',
    'inventory.unit.package': 'Упаковка',
    'inventory.category.beauty': 'Косметика',
    'inventory.category.hair': 'Волосы',
    'inventory.category.nails': 'Ногти',
    'inventory.category.equipment': 'Оборудование',
    'inventory.category.other': 'Другое',
    'inventory.emptyState': 'Нет товаров на складе',
    'inventory.emptyState.desc': 'Начните добавлять товары в ваш склад',
    'inventory.quickSale': 'Быстрая продажа',
    'inventory.quickSale.title': 'Быстрая продажа',
    'inventory.quickSale.addProduct': 'Добавить товар',
    'inventory.quickSale.cart': 'Корзина',
    'inventory.quickSale.empty': 'Корзина пуста',
    'inventory.quickSale.complete': 'Завершить продажу',
    'inventory.return': 'Возврат товара',
    'inventory.return.title': 'Возврат товара',
    'inventory.return.product': 'Товар',
    'inventory.return.quantity': 'Количество возврата',
    'inventory.return.reason': 'Причина',
    'inventory.return.confirm': 'Подтвердить возврат',
    'inventory.lowStockAlert': 'Низкие остатки',
    'inventory.lowStockAlert.desc': '{count} товаров с низкими остатками',
    'inventory.lowStockAlert.view': 'Посмотреть товары',
    
    // Services Management
    'services.title': 'Услуги',
    'services.newService': 'Добавить услугу',
    'services.editService': 'Редактировать услугу',
    'services.name': 'Название услуги',
    'services.nameRu': 'Название услуги (русский)',
    'services.namePlaceholder': 'Например: Мужская стрижка',
    'services.nameRuPlaceholder': 'Например: Мужская стрижка',
    'services.price': 'Цена',
    'services.duration': 'Длительность',
    'services.color': 'Цвет',
    'services.description': 'Описание',
    'services.descriptionPlaceholder': 'Краткое описание услуги...',
    'services.descriptionRuPlaceholder': 'Краткое описание услуги...',
    'services.edit': 'Редактировать',
    'services.delete': 'Удалить',
    'services.created': 'Услуга успешно создана',
    'services.updated': 'Услуга успешно обновлена',
    'services.deleted': 'Услуга успешно удалена',
    'services.deleteConfirm': 'Удаление услуги',
    'services.deleteConfirmMessage': 'Удалить услугу "{name}"? Это действие нельзя отменить.',
    'services.searchPlaceholder': 'Поиск услуги...',
    'services.noResultsFound': 'Результаты не найдены',
    'services.noServicesYet': 'В системе еще нет услуг',
    'services.createFirst': 'Создать первую услугу',
    'services.emptyState': 'Нет услуг',
    'services.emptyState.desc': 'Начните добавлять услуги в систему',
    'services.errors.nameRequired': 'Название услуги обязательно',
    'services.errors.priceInvalid': 'Цена должна быть положительной',
    'services.errors.durationInvalid': 'Длительность должна быть не менее одной минуты',
    
    // Care Instructions
    'careInstructions.title': 'Инструкции по уходу',
    'careInstructions.description': 'Управление инструкциями по уходу для клиентов после услуг',
    'careInstructions.newInstruction': 'Добавить инструкцию',
    'careInstructions.editInstruction': 'Редактировать инструкцию',
    'careInstructions.instructionTitle': 'Заголовок',
    'careInstructions.instructionTitleRu': 'Заголовок (русский)',
    'careInstructions.instructionContent': 'Содержание инструкции',
    'careInstructions.instructionContentRu': 'Содержание (русский)',
    'careInstructions.selectService': 'Выберите услугу',
    'careInstructions.noService': 'Общая (для всех услуг)',
    'careInstructions.created': 'Инструкция успешно создана',
    'careInstructions.updated': 'Инструкция успешно обновлена',
    'careInstructions.deleted': 'Инструкция успешно удалена',
    'careInstructions.deleteConfirm': 'Удалить эту инструкцию?',
    'careInstructions.sendInstructions': 'Отправить инструкции по уходу',
    'careInstructions.downloadPDF': 'Скачать PDF',
    'careInstructions.sendWhatsApp': 'Отправить в WhatsApp',
    'careInstructions.noInstructions': 'Нет инструкций по уходу',
    'careInstructions.noInstructionsForService': 'Нет инструкций для этой услуги',
    
    // Settings - Service Colors
    'settings.serviceColors': 'Цвета услуг',
    'settings.serviceColors.desc': 'Настройте цвета для каждого типа услуги',
    'settings.serviceColors.save': 'Сохранить цвета',
    
    // Services (for visits)
    'service.haircut': 'Стрижка',
    'service.coloring': 'Окрашивание',
    'service.smoothing': 'Выпрямление',
    'service.facial': 'Уход за лицом',
    'service.manicure': 'Маникюр',
    'service.pedicure': 'Педикюр',
    'service.haircutColoring': 'Стрижка + окрашивание',
    'service.hairTreatment': 'Уход за волосами',
    'service.consultation': 'Консультация',
    'service.meeting': 'Встреча',
    'service.advertising': 'Реклама',
    'service.other': 'Другое',
    
    // Duration options
    'duration.30min': '30 минут',
    'duration.45min': '45 минут',
    'duration.60min': '60 минут (час)',
    'duration.90min': '90 минут (полтора часа)',
    'duration.120min': '120 минут (два часа)',
    
    // Payments
    'payments.title': 'Платежи',
    'payments.subtitle': 'Управление платежами и доходами',
    'payments.addNew': 'Добавить платёж',
    'payments.createLink': 'Создать ссылку на оплату',
    'payments.cashPayment': 'Наличные',
    'payments.cashPaymentSuccess': 'Оплата записана',
    'payments.createFirst': 'Создать первую ссылку для оплаты',
    'payments.client': 'Клиент',
    'payments.selectClient': 'Выберите клиента',
    'payments.amount': 'Сумма',
    'payments.amountPlaceholder': '100.00',
    'payments.description': 'Описание',
    'payments.descriptionPlaceholder': 'Описание платежа (необязательно)',
    'payments.status': 'Статус',
    'payments.paid': 'Оплачено',
    'payments.pending': 'Ожидание',
    'payments.failed': 'Ошибка',
    'payments.refunded': 'Возвращено',
    'payments.cancelled': 'Отменено',
    'payments.method': 'Способ оплаты',
    'payments.cash': 'Наличные',
    'payments.card': 'Кредитная карта',
    'payments.bankTransfer': 'Банковский перевод',
    'payments.total': 'Итого',
    'payments.filter': 'Фильтр',
    'payments.all': 'Все',
    'payments.fromDate': 'С даты',
    'payments.toDate': 'До даты',
    'payments.totalMonth': 'Всего платежей за месяц',
    'payments.successfulTransactions': 'Успешных транзакций',
    'payments.avgTransaction': 'Средняя транзакция',
    'payments.noPayments': 'Нет платежей',
    'payments.unknown': 'Неизвестно',
    'payments.copyLink': 'Скопировать ссылку',
    'payments.openLink': 'Открыть ссылку',
    'payments.transactionId': 'ID транзакции',
    'payments.linkCopied': 'Ссылка скопирована в буфер обмена',
    'payments.successMessage': 'Ссылка для оплаты успешно создана!',
    'payments.sendLinkToClient': 'Отправьте ссылку клиенту для безопасной оплаты',
    'payments.failedMessage': 'Ошибка платежа',
    'payments.creating': 'Создание ссылки...',
    'payments.paymentSuccess': 'Платёж выполнен успешно!',
    'payments.paymentCanceled': 'Платёж отменён',
    'payments.filterByMethod': 'Фильтр по способу оплаты',
    'payments.filterByStatus': 'Фильтр по статусу',
    'payments.filterByDate': 'Фильтр по дате',
    'payments.filterByClient': 'Фильтр по клиенту',
    'payments.method.cash': 'Наличные',
    'payments.method.bit': 'Bit',
    'payments.method.credit': 'Кредитная карта',
    'payments.method.stripe': 'Stripe',
    'payments.method.bankTransfer': 'Банковский перевод',
    'payments.method.phoneCredit': 'Телефонная оплата',
    
    // Subscriptions
    'subscriptions.create': 'Оформить подписку',
    'subscriptions.createNew': 'Создать подписку',
    'subscriptions.selectClient': 'Выберите клиента',
    'subscriptions.amount': 'Сумма',
    'subscriptions.amountPlaceholder': 'Введите сумму',
    'subscriptions.interval': 'Период',
    'subscriptions.monthly': 'Месячный',
    'subscriptions.weekly': 'Еженедельный',
    'subscriptions.yearly': 'Годовой',
    'subscriptions.creating': 'Создание...',
    
    // SMS
    'sms.title': 'SMS сообщения',
    'sms.subtitle': 'Управление SMS рассылками для клиентов',
    'sms.sendNew': 'Отправить новое сообщение',
    'sms.newMessage': 'Новое сообщение',
    'sms.campaignName': 'Название кампании',
    'sms.campaignNamePlaceholder': 'Например: Напоминание о визите',
    'sms.messageContent': 'Текст сообщения',
    'sms.messageContentPlaceholder': 'Привет! Напоминаем о вашем визите...',
    'sms.sendingType': 'Тип отправки',
    'sms.sendToAll': 'Отправить всем',
    'sms.sendToAllDesc': 'Отправить всем клиентам в системе',
    'sms.sendToOne': 'Отправить одному клиенту',
    'sms.sendToOneDesc': 'Выбрать конкретного клиента',
    'sms.sendToInactive': 'Неактивные клиенты',
    'sms.sendToInactiveDesc': 'Клиенты, которые не посещали недавно',
    'sms.messageHistory': 'Сообщение отправлено {count} получателям',
    'sms.recipient': 'Получатель',
    'sms.recipients': 'Получатели',
    'sms.message': 'Текст сообщения',
    'sms.send': 'Отправить',
    'sms.history': 'История рассылок',
    'sms.sent': 'Отправлено',
    'sms.failed': 'Ошибка',
    'sms.delivered': 'Доставлено',
    'sms.completed': 'Завершено',
    'sms.sending': 'Отправка',
    'sms.draft': 'Черновик',
    'sms.selectClient': 'Выберите клиента',
    'sms.messagePlaceholder': 'Введите текст сообщения...',
    'sms.remaining': 'символов осталось',
    'sms.charactersCount': '0 символов (0 SMS)',
    'sms.singleMessage': 'Одно сообщение',
    'sms.multiPartMessage': 'Многочастное сообщение',
    'sms.sendNow': 'Отправить сейчас',
    'sms.confirmSend': 'Подтверждение отправки',
    'sms.confirmMessage': 'Вы уверены, что хотите отправить сообщение {count} получателям?',
    'sms.multiPartWarning': 'Внимание: каждое сообщение будет отправлено в {parts} частях',
    'sms.willBeSentTo': 'Сообщение будет отправлено {count} получателям',
    'sms.costPerMessage': 'Каждое сообщение будет отправлено в {parts} частях (стоимость: {parts}x)',
    'sms.inactiveDays': 'Не посещали в течение',
    'sms.days': 'дней',
    'sms.noCampaigns': 'Нет рассылок',
    'sms.createNew': 'Создайте новую рассылку выше',
    
    // Stats
    'stats.title': 'Статистика',
    'stats.subtitle': 'Общий обзор бизнеса',
    'stats.revenue': 'Доход',
    'stats.revenueByMonth': 'Доход по месяцам',
    'stats.visitsByMonth': 'Визиты по месяцам',
    'stats.byMonth': 'По месяцам',
    'stats.byService': 'По услугам',
    'stats.topClients': 'Топ 5 клиентов',
    'stats.totalPayments': 'Всего платежей',
    'stats.trends': 'Тенденции',
    'stats.export': 'Экспорт данных',
    'stats.noData': 'Нет данных для отображения',
    
    // Analytics
    'analytics.title': 'Отчёты и аналитика',
    'analytics.subtitle': 'Глубокий анализ бизнес-данных',
    'analytics.paymentMethods': 'Распределение способов оплаты',
    'analytics.revenueOverTime': 'Доход за период',
    'analytics.totalRevenue': 'Общий доход',
    'analytics.avgTransaction': 'Средняя транзакция',
    'analytics.totalTransactions': 'Всего транзакций',
    'analytics.period': 'Период',
    'analytics.daily': 'Ежедневно',
    'analytics.weekly': 'Еженедельно',
    'analytics.monthly': 'Ежемесячно',
    'analytics.filterByMethod': 'Фильтр по способу оплаты',
    'analytics.allMethods': 'Все способы',
    
    // Partners
    'partners.title': 'Партнёрские предложения',
    'partners.subtitle': 'Откройте для себя рекомендуемые продукты и услуги для вашего бизнеса',
    'partners.noOffers': 'Нет доступных предложений',
    'partners.checkLater': 'Проверьте позже',
    'partners.details': 'Подробнее',
    
    // Common
    'common.loading': 'Загрузка данных...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.minutes': 'минут',
    'common.close': 'Закрыть',
    'common.back': 'Назад',
    'common.logout': 'Выйти',
    'common.add': 'Добавить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.view': 'Просмотр',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.import': 'Импорт',
    'common.refresh': 'Обновить',
    'common.submit': 'Отправить',
    'common.reset': 'Сбросить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.ok': 'ОК',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    'common.required': 'Обязательное поле',
    'common.optional': 'Необязательно',
    'common.select': 'Выбрать',
    'common.selectAll': 'Выбрать все',
    'common.deselectAll': 'Снять выбор',
    'common.noData': 'Нет данных',
    'common.noResults': 'Нет результатов',
    'common.showing': 'Показано',
    'common.of': 'из',
    'common.items': 'элементов',
    'common.page': 'Страница',
    'common.perPage': 'на странице',
    'common.total': 'Всего',
    'common.actions': 'Действия',
    'common.date': 'Дата',
    'common.time': 'Время',
    'common.status': 'Статус',
    'common.active': 'Активен',
    'common.inactive': 'Неактивен',
    'common.enabled': 'Включено',
    'common.disabled': 'Отключено',
    'common.description': 'Описание',
    'common.name': 'Название',
    'common.email': 'Email',
    'common.phone': 'Телефон',
    'common.address': 'Адрес',
    'common.notes': 'Заметки',
    'common.created': 'Создано',
    'common.updated': 'Обновлено',
    'common.createdAt': 'Дата создания',
    'common.updatedAt': 'Дата обновления',
    'common.deleteConfirm': 'Вы уверены, что хотите удалить?',
    'common.cannotUndo': 'Это действие нельзя отменить',
    'common.saving': 'Сохранение...',
    'common.deleting': 'Удаление...',
    'common.notAvailable': 'Недоступно',
    
    // Error page
    'error.message': 'Что-то пошло не так. Пожалуйста, попробуйте снова или обратитесь в поддержку.',
    'error.retry': 'Попробовать снова',
    'error.backHome': 'Вернуться на главную',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('he')

  useEffect(() => {
    // Load language from localStorage
    const saved = localStorage.getItem('trinity-language') as Language
    if (saved && (saved === 'he' || saved === 'ru')) {
      setLanguageState(saved)
      applyLanguage(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('trinity-language', lang)
    applyLanguage(lang)
  }

  const applyLanguage = (lang: Language) => {
    const dir = lang === 'he' ? 'rtl' : 'ltr'
    document.documentElement.setAttribute('lang', lang)
    document.documentElement.setAttribute('dir', dir)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const dir = language === 'he' ? 'rtl' : 'ltr'

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
